<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_prenom</name>
   <tag></tag>
   <elementGuidId>50a27f04-1bbe-485a-809f-4b2dc2104063</elementGuidId>
   <imagePath>Screenshots/Targets/Page_MyTower/input_First Name_prenom.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prenom</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_MyTower/input_First Name_prenom.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6452f7a5-386c-4f1e-9329-ef9b8edfe880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>b2336b91-c531-48f0-a03c-e9679b84e670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prenom</value>
      <webElementGuid>a80b048e-7bba-4c9b-a087-bc1ccd77af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prenom</value>
      <webElementGuid>0b71aa4c-ec5b-4ed8-8e8f-36201ffd176b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>9e579beb-0205-4cc5-911b-44a71414ccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prenom&quot;)</value>
      <webElementGuid>4fc81827-4bc1-45f0-886b-a7cc5b9d1a2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prenom']</value>
      <webElementGuid>ec33f452-f00c-43fd-ae0e-587f86f4c161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[2]/aw-wizard/div/aw-wizard-step/form/div/div[2]/input</value>
      <webElementGuid>2dc7ef17-8460-470c-ab6f-4d2c8a0bf7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d059f5b6-9e07-4399-a7e9-3a79837fcf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prenom' and @name = 'prenom' and @placeholder = 'First Name']</value>
      <webElementGuid>f0811e2f-4a3c-4795-91e8-d8c17e2c5986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
