<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_nom</name>
   <tag></tag>
   <elementGuidId>659d201d-afa4-44b9-8bdd-3b0a8479b8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>191fd373-ffc7-448d-b36a-105345dd8a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>cbb8041c-ec58-4132-bdcb-794672f7cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nom</value>
      <webElementGuid>5ca817c8-68c2-4c50-80d0-3aa5b06f6bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nom</value>
      <webElementGuid>8ad4eac9-e59f-403b-875c-caa5785cc283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>0a4358de-fb34-4fa6-a21f-75b9e0522836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nom&quot;)</value>
      <webElementGuid>530442e6-a4d0-4a86-92ca-4fc68f8f7d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nom']</value>
      <webElementGuid>d47be494-79b0-46ed-8833-a9684f906b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[2]/aw-wizard/div/aw-wizard-step/form/div/div/input</value>
      <webElementGuid>0e2d308e-b902-42d2-a587-333ab3499be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0d9d23c2-2931-4857-9c96-cffc1474e9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nom' and @name = 'nom' and @placeholder = 'Last Name']</value>
      <webElementGuid>132df744-a804-44d1-9b50-88527983b590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
