<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name</name>
   <tag></tag>
   <elementGuidId>874eb241-b634-475a-aad3-e6f09f9238d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd5a358-f368-4019-a7d4-e065df320d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d57394e3-5c5b-4937-acb3-8de37530b290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bb3e2eb0-abfe-4869-915f-4bfe72cf5fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4d4c4d9c-a168-412c-9dab-803096a3fa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>daacb51b-a8a8-4d86-880c-393e5b4c8d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tel&quot;)</value>
      <webElementGuid>f868ee12-28c6-4832-98a4-bf5afd733ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tel']</value>
      <webElementGuid>06dfc983-7933-4642-ae35-aac5d0337880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-user-details/div/div[2]/div/div[4]/input</value>
      <webElementGuid>c921d391-0c53-4e32-8326-af9b7ee24af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>eb7844e6-8767-48b4-8e22-2d8d39458d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tel' and @name = 'tel' and @type = 'text']</value>
      <webElementGuid>cc7cf16e-7bfe-4945-a3b4-a8585a698652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
