<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Establishment</name>
   <tag></tag>
   <elementGuidId>de1db19c-3ba1-4c86-9405-e1468190c9b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#etablissement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='etablissement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf023587-5a0a-4f6a-a474-9d7a5c5dcfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-star-inserted ng-valid</value>
      <webElementGuid>bd101b74-d68b-4e34-a2c1-23a31cb91b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>etablissement</value>
      <webElementGuid>263e97ab-3844-4bea-9d1f-bc0acc72e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>etablissement</value>
      <webElementGuid>a896375b-6134-4d6a-a56a-dc78fd0412d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an establishment MyTower Operations  ADV SLB-GSS  Quotation Desk (EXN)  Demo TDC  4PL HUB  CT1.2  CT1.1  CT1.1  ADV SLB </value>
      <webElementGuid>add9a0ce-7df2-40e5-8463-5f9dffdf028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etablissement&quot;)</value>
      <webElementGuid>1418d886-49cd-4a36-9c11-cebf11d1b033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='etablissement']</value>
      <webElementGuid>5cad37f4-ee98-40e3-8690-f5c0283e7fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-user-details/div/div[2]/select</value>
      <webElementGuid>02e94b8d-e83f-4dce-8157-5653390dd3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Establishment:'])[1]/following::select[1]</value>
      <webElementGuid>b3f9b8c9-ce9d-4144-8f56-8688ed0df791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name:'])[1]/following::select[1]</value>
      <webElementGuid>ad5e89dc-f310-4e3a-804e-81cf1053eb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[3]/preceding::select[1]</value>
      <webElementGuid>37c5e641-e74d-4553-91b9-52c53878f765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate with a profile'])[1]/preceding::select[1]</value>
      <webElementGuid>2e04c89b-2645-4a24-8144-c42c3f873fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dfceb5ec-7ccb-4675-859a-21e044f81808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'etablissement' and @name = 'etablissement' and (text() = 'Select an establishment MyTower Operations  ADV SLB-GSS  Quotation Desk (EXN)  Demo TDC  4PL HUB  CT1.2  CT1.1  CT1.1  ADV SLB ' or . = 'Select an establishment MyTower Operations  ADV SLB-GSS  Quotation Desk (EXN)  Demo TDC  4PL HUB  CT1.2  CT1.1  CT1.1  ADV SLB ')]</value>
      <webElementGuid>4eb98398-b4b2-4863-b4ca-998c666ff67a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
