<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>5af219f6-b0f4-48cf-b2f6-aa43353fe0d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sidebar-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app-header&quot;]/app-header/div/div/div[2]/div[1]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cd74c8b-7af7-4641-8e89-6848e975ecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-title</value>
      <webElementGuid>96f14a75-f627-4dc9-96ed-b6fa8b9e7b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modifier</value>
      <webElementGuid>d9248102-bb5b-487b-8c42-53d7f8885cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/div[1]/div[@class=&quot;actionbar-wrapper&quot;]/div[@class=&quot;btn-action-wrapper&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/button[@class=&quot;btn btn-xs btn-tertiary ng-star-inserted&quot;]/span[@class=&quot;sidebar-title&quot;]</value>
      <webElementGuid>cbdaba9c-cf28-4158-b51b-a7a47d85b40e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/div/div/div[2]/div/button/span[2]</value>
      <webElementGuid>93a328b8-b8a0-49b2-a70d-44e580181ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSY-A23511'])[1]/following::span[2]</value>
      <webElementGuid>694fcd95-38ed-4834-9c5d-51fb7f07f6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::span[2]</value>
      <webElementGuid>7fa2b59c-146c-47bf-829d-430dc8b4951c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dupliquer'])[1]/preceding::span[2]</value>
      <webElementGuid>71cdc0b4-6da9-4b2c-8a2e-08ee1870358e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associer à une déclaration'])[1]/preceding::span[4]</value>
      <webElementGuid>ac96b3a5-3663-4479-8d62-bafd1aa060ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modifier']/parent::*</value>
      <webElementGuid>4f8842b6-cfc2-4651-a0c8-94ddea7605c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>086f1f11-577c-42e1-873b-437cfd73193d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Modifier' or . = 'Modifier')]</value>
      <webElementGuid>1140e94e-3313-4873-bb1e-3589698d2383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
