<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User_Carrier</name>
   <tag></tag>
   <elementGuidId>b0a9186e-8e5e-46b3-926c-f0f833783a49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a95a763d1aed-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a0fe98f-7fa5-4ded-9213-bf598878a04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>170b2020-f3d4-456f-8a9d-cb91bf7f09b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6823155f-cffa-41a3-b15e-2b141614fdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>409b0692-bc77-4df0-b159-778a35242f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a95a763d1aed-1</value>
      <webElementGuid>bbf14ea4-0f80-4200-8885-67d7c8ad8ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User_Carrier testA</value>
      <webElementGuid>1ee03a01-4641-4da8-91cd-0d25b09281f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a95a763d1aed-1&quot;)</value>
      <webElementGuid>ae65dbb9-158a-4f3b-aa8c-aeace4f7942d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a95a763d1aed-1']</value>
      <webElementGuid>b333c2dc-e9b4-4f85-ae37-c294b08847b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a95a763d1aed']/div/div[2]/div</value>
      <webElementGuid>6d6b762d-91fc-42d2-b28b-5181bf4b9fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionnez un utilisateur ...'])[3]/following::div[5]</value>
      <webElementGuid>e3acefe6-b92c-4d1d-8a85-85ffab179c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demande reçue par le transporteur'])[1]/following::div[14]</value>
      <webElementGuid>2008bf92-6021-4034-859e-7e241bb842ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter cotation'])[1]/preceding::div[1]</value>
      <webElementGuid>8d29ddf3-6905-4c1b-9451-02a5c2b8431c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>de52cade-63c5-44f5-ac78-05559114e0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a95a763d1aed-1' and (text() = 'User_Carrier testA' or . = 'User_Carrier testA')]</value>
      <webElementGuid>e2f7e7f9-adc3-4f5a-ad8b-1215b7ea215d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
