<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select_Carriers</name>
   <tag></tag>
   <elementGuidId>43bea7af-cc05-45a2-be71-a1ce3d682183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-untouched.ng-pristine.ng-valid.ng-select-focused.ng-select-opened.ng-select-bottom > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div[1]/div/div[2]/div/div/div[1]/app-autocomplete/ng-select/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04580bd8-58ff-4cd6-88e9-3a753254e682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d94caa59-cba2-4152-8e55-9f197462f1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c400ef1-9622-46fb-aeef-f739a91cad76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b118eecb-6e22-4a17-8e7f-054d10574f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72e33c56-39ab-47a3-99cc-1698973d31a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a95a763d1aed</value>
      <webElementGuid>c7148ac9-4313-458d-ad4d-e60238b5c0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0153125e-744b-4666-a163-c0a5495fb685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a95a763d1aed</value>
      <webElementGuid>6ddb769c-a9c6-424c-84f4-413760397939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a95a763d1aed-0</value>
      <webElementGuid>6b1688fd-8228-4570-9cc9-85d38f0bfcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-visualisation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper col-md-12 padding-0&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;new-design_details-contents col-md-12 padding-0&quot;]/div[@class=&quot;collapsible-blocs&quot;]/div[@class=&quot;middle-blocs col-md-6 col-sm-12 col-xs-12 padding-4&quot;]/app-demande-creation-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;create-wf-root form-card-no-border&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-pricing[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid relativePostion&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row margin-top-15 ng-star-inserted&quot;]/div[@class=&quot;pull-right&quot;]/div[@class=&quot;float-left generic-inputs__style tr-autocomplete&quot;]/app-autocomplete[1]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-valid ng-select-focused ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>0f9e69b6-c248-4a11-9d80-aef914411bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[54]</value>
      <webElementGuid>467ee7d0-c063-4d9e-a3c7-ad59d1e7f7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div/div/div[2]/div/div/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>0afbb894-15ec-4025-b155-2262316deb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>c787d3e6-6742-4454-8b0e-281bd4eceeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d7e284b4-19b7-432f-a474-05ae5ab5a54b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
