<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Activated</name>
   <tag></tag>
   <elementGuidId>63878758-e024-4c88-95a6-c2d9dfb68135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-inputswitch-slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/div[6]/div/p-inputswitch/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73dc776e-d86f-4de5-a211-8bb0ca1c0675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputswitch-slider</value>
      <webElementGuid>8769934c-61c5-4aa0-9467-787fff19b945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[1]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 new-formcontrol&quot;]/div[@class=&quot;col-md-8 padding-left-0-important padding-right-0-important&quot;]/p-inputswitch[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ui-inputswitch ui-widget&quot;]/span[@class=&quot;ui-inputswitch-slider&quot;]</value>
      <webElementGuid>3c79686d-96e2-4fbe-9223-d9d8d284e33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/div[6]/div/p-inputswitch/div/span</value>
      <webElementGuid>04b576d8-38c5-4be0-9a6d-509a8bcff512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-inputswitch/div/span</value>
      <webElementGuid>6db1f93c-97b3-4dcb-9466-6f8900bb2c4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
