<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Road</name>
   <tag></tag>
   <elementGuidId>ac6715df-c6cc-4f95-b95f-6afcaf1ddd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-road</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ng-option ng-star-inserted'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>666bcaac-1395-49fc-aca2-5f01d68c3224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-road</value>
      <webElementGuid>bd64579c-a08b-4331-a121-83c43d2a6c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a935da2a86ff-0&quot;)/span[@class=&quot;ng-star-inserted&quot;]/app-flag[1]/span[1]/i[@class=&quot;fa fa-road&quot;]</value>
      <webElementGuid>82c6189d-f006-4ba5-9921-0cd21e709495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a935da2a86ff-0']/span/app-flag/span/i</value>
      <webElementGuid>d3855598-aa8e-4e0e-b73a-d8e9a395dcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-flag/span/i</value>
      <webElementGuid>61dcdffc-b2ad-4177-839e-c6b1d78bb60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
