<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label</name>
   <tag></tag>
   <elementGuidId>30857c12-3c03-47da-afe0-9b0126af256d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;libelle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='libelle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2e6024d-9675-48a1-a1c8-555f056073f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3df10b4f-74ed-4720-ab8a-70e467ee711d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>libelle</value>
      <webElementGuid>2e81690b-5191-44b5-97ec-006a6ad2d840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10438d22-cb60-4616-aa96-6c5002eadbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[1]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 new-formcontrol&quot;]/div[@class=&quot;col-md-8 padding-left-0-important padding-right-0-important&quot;]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>f0d9caf0-01d3-4156-81c7-5a52dcd893b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='libelle']</value>
      <webElementGuid>f2f41f45-bc5f-4a36-8497-5c9b0883585a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>36d72861-787b-486b-9996-0f08aeb11916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8eb179a9-dbc3-49f9-8f86-4d7d1f8e52fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'libelle' and @type = 'text']</value>
      <webElementGuid>8bbec304-b3e1-45ed-8ca8-4996ee063199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
