<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order</name>
   <tag></tag>
   <elementGuidId>a6bc1919-e824-4800-bf6d-0e6c0edd8a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ordre&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ordre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>762fe780-5cbb-4dfd-84bf-05dba359ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>3bf1144f-3760-4766-9554-20bbddfe467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ordre</value>
      <webElementGuid>76a25fb5-2709-44ab-9e9c-26cb60791168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>35d91b60-a276-4311-ad05-4677db39421c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[1]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 new-formcontrol&quot;]/div[@class=&quot;col-md-8 padding-left-0-important padding-right-0-important&quot;]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>eb42c08e-ca0b-4c53-8a46-4c2d8827480b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ordre']</value>
      <webElementGuid>1fe907e0-76bb-44d9-ab37-8b47ee0c1a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>e6018e16-f6ad-4c2c-96db-7c40c17270f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7e315390-d636-453d-8bda-806b2a371f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ordre' and @type = 'number']</value>
      <webElementGuid>f4e73ba3-a631-41f6-935b-cda8fc6d0f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
