<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Color</name>
   <tag></tag>
   <elementGuidId>ff6e3638-d9f0-4453-a0ca-360f856e63b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ui-colorpicker-preview.ui-inputtext.ui-state-default.ui-corner-all.ng-tns-c30-4.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e61b8f9e-2baa-4089-848f-13bcda0b8735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-colorpicker-preview ui-inputtext ui-state-default ui-corner-all ng-tns-c30-4 ng-star-inserted</value>
      <webElementGuid>94763a91-9cc0-44c0-937f-bb4f04ddd4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f616b1dc-2c6b-48b0-9d05-231fb6a14425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0db1b394-efc4-442d-bd1c-0329ec12b3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-star-inserted ng-invalid ng-dirty ng-touched&quot;]/div[1]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 new-formcontrol&quot;]/div[@class=&quot;col-md-8 padding-left-0-important padding-right-0-important&quot;]/p-colorpicker[@class=&quot;ng-tns-c30-4 ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;ng-tns-c30-4 ui-colorpicker ui-widget ui-colorpicker-overlay&quot;]/input[@class=&quot;ui-colorpicker-preview ui-inputtext ui-state-default ui-corner-all ng-tns-c30-4 ng-star-inserted&quot;]</value>
      <webElementGuid>aafeb59e-3f9b-41b0-9f3b-d703fa206541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>c38e7976-89c4-4190-8af0-cf5e81586c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/div[3]/div/p-colorpicker/div/input</value>
      <webElementGuid>4a53ada8-3c41-4e6a-8468-63ad248f9dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-colorpicker/div/input</value>
      <webElementGuid>408582ae-b860-4575-87ae-40cac54a9da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>52647927-c629-44bb-a11a-686dc42ea9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
