<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_From_Address_for_Shipper</name>
   <tag></tag>
   <elementGuidId>3d73c1e5-3eb0-4c46-b27b-10237f63a7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div[1]/div/div[2]/app-step-expedition/div/div[3]/div/div/div/div[2]/p-virtualscroller/div/div/ul/cdk-virtual-scroll-viewport/div[1]/li[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f032d2b-56c5-4a0d-bfb3-fd319fa3f3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 card ng-star-inserted</value>
      <webElementGuid>1044f9d2-1bea-4702-8050-2d6a615c60d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XIN FENG ELECTRICAL LTDNO. 16 SOUTH GONGYE AVENUE, TAIFENG INDUSTRIAL ZONE, XIAOLAN TOWNZHONGSHAN CITY, GUANGDONG PROVINCEChina</value>
      <webElementGuid>a6901c87-bf59-44ca-9dbc-d0a41a1825ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;options show-options&quot;]/div[@class=&quot;options-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;adresse-wrapper ng-star-inserted&quot;]/p-virtualscroller[1]/div[@class=&quot;ui-virtualscroller ui-widget&quot;]/div[@class=&quot;ui-virtualscroller-content ui-widget-content&quot;]/ul[@class=&quot;ui-virtualscroller-list&quot;]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/li[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-12 card ng-star-inserted&quot;]</value>
      <webElementGuid>d528ff4c-f038-4d1e-b413-54165dff148e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div[3]/div/div/div/div[2]/p-virtualscroller/div/div/ul/cdk-virtual-scroll-viewport/div/li[2]/div</value>
      <webElementGuid>c428770e-3827-4c7e-bc4b-51c8acdf85ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='France'])[1]/following::div[1]</value>
      <webElementGuid>4a799e1e-0a0e-424f-bb57-7643b6c36831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le Plessis belleville'])[1]/following::div[2]</value>
      <webElementGuid>065e008b-b9b6-406c-b1e3-d597d1e80052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>f46ba730-b9f8-46c5-8d0d-995974d9d2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'XIN FENG ELECTRICAL LTDNO. 16 SOUTH GONGYE AVENUE, TAIFENG INDUSTRIAL ZONE, XIAOLAN TOWNZHONGSHAN CITY, GUANGDONG PROVINCEChina' or . = 'XIN FENG ELECTRICAL LTDNO. 16 SOUTH GONGYE AVENUE, TAIFENG INDUSTRIAL ZONE, XIAOLAN TOWNZHONGSHAN CITY, GUANGDONG PROVINCEChina')]</value>
      <webElementGuid>748bef20-642c-40f9-9346-c8d9de5f9d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
