<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_Address_For_Shipper</name>
   <tag></tag>
   <elementGuidId>3ace5c00-6a4c-4ab7-959b-bdffa7481916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div[1]/div/div[2]/app-step-expedition/div/div[1]/div[1]/div[4]/adresse-for-shipping/fieldset/div/div/div/div[1]/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b7ddd02-a4ba-411a-80c3-1f6aacc0319c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd29f2de-f89c-49af-9cfb-2d35a07e6646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6195ef5a-9ff6-4d75-a9c3-63bda288a670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 col-xs-12&quot;]/adresse-for-shipping[1]/fieldset[@class=&quot;border-0 margin-0-important&quot;]/div[@class=&quot;adress-wrapper&quot;]/div[@class=&quot;fields-wrapper&quot;]/div[@class=&quot;show-for-creation clearfix&quot;]/div[@class=&quot;col-md-12 padding-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8 col-xs-12 padding-right-0 input-wrapper&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>0b3f1596-3ecb-41e3-a401-02fb0b06fe84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>16f331fe-7b85-40bb-b700-e19b99638bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[4]/adresse-for-shipping/fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>afb23035-0e3f-4e03-b1d0-558fade78273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/adresse-for-shipping/fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>ed242442-165f-4b5f-ac9f-5fa58920de00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>60a10b7a-3cd7-48a8-aa36-4089d5ae436a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
