<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice_Currency_Shipper</name>
   <tag></tag>
   <elementGuidId>71a0089e-79e1-4edb-ad0a-1854a159a357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div[1]/div[1]/div[3]/app-step-reference/div/div[1]/form/div[2]/div/fieldset/div[3]/div[1]/app-autocomplete/ng-select/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-pristine.ng-invalid.ng-select-top.ng-touched.ng-select-focused.ng-select-opened > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04a97b98-170d-4860-b2ed-faa9abd8bba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7b8a6463-03a3-4503-8943-f0dde85ecf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d56e65f3-b0be-4410-ad43-3d3c19b5229a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df67b27f-4e33-4003-9270-78e821d94e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d016288a-c52b-4a91-a348-c104003b2331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>aeeb61c8e517</value>
      <webElementGuid>55b98dfd-466d-43cc-b72e-190b0afe6205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>763098f2-6011-4f12-9b35-38c2cb9eba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>aeeb61c8e517</value>
      <webElementGuid>7ced7a59-113f-4b7c-a099-207f76af2bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>aeeb61c8e517-6</value>
      <webElementGuid>f0c93b10-1eb3-4007-8576-e7ee6f87ad5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-reference[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row margin-bottom-15&quot;]/div[@class=&quot;col-md-12&quot;]/fieldset[1]/div[@class=&quot;col-md-12  d-flex-ai-c generic-inputs__style flex-wrap&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12&quot;]/app-autocomplete[@class=&quot;ng-star-inserted&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-pristine ng-invalid ng-select-top ng-touched ng-select-focused ng-select-opened&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>0b761319-f005-409e-a0a0-a9ced70ab149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>aaae9040-82f5-48b3-b255-bb6605d55da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[3]/app-step-reference/div/div/form/div[2]/div/fieldset/div[3]/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>818ee371-6619-41e7-927d-10690889e752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>99a836fb-3cb3-4a9d-8618-58e2f9781047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>1efb7ea8-095b-41cb-9744-3abcdce1c0fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
