<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Settings</name>
   <tag></tag>
   <elementGuidId>27d35137-412d-49e5-a6ad-9e35b6cbb42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Settings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Settings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a90024e7-0636-494d-985f-4fd904885e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>c0eac1cc-f155-43b0-a0fb-16dcf509b3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/account-settings</value>
      <webElementGuid>d1747fb6-d04d-4715-87c0-8a82a3ed18bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/account-settings</value>
      <webElementGuid>f4f70532-98d5-4e45-98b2-e3b676ec41d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>390583c2-bb46-4a51-9d16-cc77521d7d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Settings&quot;)</value>
      <webElementGuid>2dd348a3-c2bc-4243-a033-ccd5ff830b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Settings']</value>
      <webElementGuid>54c41d60-f839-42b7-845b-953360dd2880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-menu']/li[7]/a</value>
      <webElementGuid>5b537f88-4783-4413-9b66-d3cccb3f6976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliance Matrix'])[1]/following::a[1]</value>
      <webElementGuid>90d9219b-4e1e-4711-a4f3-89f905eeb92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/following::a[2]</value>
      <webElementGuid>5152f9bb-3c9f-4698-9d1d-0801b5c1e573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLB-04187'])[1]/preceding::a[4]</value>
      <webElementGuid>23351167-be6a-49b0-9016-ef5681cc6d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/app/user/settings/account-settings')])[2]</value>
      <webElementGuid>e89aeefb-2630-40dc-b547-79a4937edfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>529fd36a-ff69-46fb-ad30-50df1f4ae05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Settings' and @href = '/app/user/settings/account-settings' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>4a231c62-fa1f-427d-bcc4-72ab88614633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
