<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_My company</name>
   <tag></tag>
   <elementGuidId>6bfe953f-bbcc-4914-820d-4b5c3aac499c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon.fa.fa-building</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-settings/div/div/nav/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ae57768-5db4-4fa8-b704-d4457095a179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-building</value>
      <webElementGuid>e6acca30-5bd5-47df-b065-620a1ecb0ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/company</value>
      <webElementGuid>16d55861-53a6-424e-95b0-67148aa9c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/company</value>
      <webElementGuid>e0e5621f-a764-4ba5-9ad2-0719815078d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My company</value>
      <webElementGuid>7b71b3f1-c886-4054-b3ec-f51f106377f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;head-tabs tabs-style-underline&quot;]/nav[1]/ul[1]/li[@class=&quot;tab-current&quot;]/a[@class=&quot;icon fa fa-building&quot;]</value>
      <webElementGuid>11314697-2400-41dc-8b72-bec6deb3a979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>eb9a4304-5a0e-45a6-bf33-252b5583e64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My community'])[2]/following::a[1]</value>
      <webElementGuid>14a9f80c-0980-497e-8618-bdf548b28b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account settings'])[1]/following::a[2]</value>
      <webElementGuid>7ef0ef82-0e3d-4c51-bcfe-642950950b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My alerts'])[1]/preceding::a[1]</value>
      <webElementGuid>b266505d-07c8-4866-9680-854ff67895c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/app/user/settings/company')])[2]</value>
      <webElementGuid>71d49865-1488-46fd-9ef6-b8769da730a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>8c8b9ffe-be19-4d85-a8bc-3673e00f9fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app/user/settings/company' and (text() = 'My company' or . = 'My company')]</value>
      <webElementGuid>b4d88f3e-d0d9-4711-9a3a-1a90d9d02356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
