<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designation</name>
   <tag></tag>
   <elementGuidId>394f7b0a-2747-4057-8246-2a06c6f3d920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;designation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='designation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dabdca8-4986-4053-ba2a-a072cd49e5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f22ef7eb-7811-4c81-bc8a-55e233737d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>designation</value>
      <webElementGuid>79d48485-2969-44d5-a9c2-f0fb2ab504a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngcontrol</name>
      <type>Main</type>
      <value>designCtrl</value>
      <webElementGuid>566dc5b2-f52c-4696-82fb-7e137957c458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d71aa916-e0e6-42f9-8dd7-e5d8b74dd660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-pristine ng-star-inserted ng-invalid ng-touched&quot;]/div[@class=&quot;form-content col-sm-12 margin-top-10&quot;]/div[@class=&quot;col-md-3 col-sm-4 col-xs-12 form-group&quot;]/div[1]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>c272a949-25e4-42b7-8c4f-660a804141f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='designation']</value>
      <webElementGuid>e60266df-16f2-4927-ab9f-729f998f94ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div[2]/div/input</value>
      <webElementGuid>96c65e61-cb67-44ec-ac94-d9793e6d6b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>09440877-d8ac-431b-85a8-0a3809e66959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'designation' and @type = 'text']</value>
      <webElementGuid>8356f0c6-5ef4-4dee-a7fb-c74fddb38bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
