<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify</name>
   <tag></tag>
   <elementGuidId>72e29cef-029a-4c58-b358-e6968454dfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-0-content']/div/p-table/div/div/div/div[2]/table/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a657915b-497c-4817-83fd-7db23337785d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textCenter colonne-generic-table gtbl-td ng-star-inserted</value>
      <webElementGuid>6258e8fc-c87c-4f02-b6f0-d36b282de6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>b9e69571-fb23-4ab5-bf97-84939061868a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> y </value>
      <webElementGuid>760b9385-90e6-458e-ae14-217e5276ce2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/p-table[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ui-table ui-widget ui-table-resizable ui-table-resizable-fit&quot;]/div[@class=&quot;ui-table-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;ui-table-scrollable-view&quot;]/div[@class=&quot;ui-table-scrollable-body&quot;]/table[@class=&quot;ui-table-scrollable-body-table&quot;]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;textCenter colonne-generic-table gtbl-td ng-star-inserted&quot;]</value>
      <webElementGuid>965448db-5436-41b8-92df-efc54da2ca9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/p-table/div/div/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>0241aab8-c029-45ac-bb76-683063aac920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='origine'])[1]/following::td[2]</value>
      <webElementGuid>84b95bfc-6557-4b63-8ba5-8b35567554c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origine'])[1]/following::td[3]</value>
      <webElementGuid>f8309c29-c0c6-49d3-b83a-10dcc939cfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='t'])[1]/preceding::td[1]</value>
      <webElementGuid>786be1a8-9ff4-4810-9861-aede5257f6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>363e3da1-4727-485b-ba17-a6c99f2dd961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'y' and (text() = ' y ' or . = ' y ')]</value>
      <webElementGuid>ee7ce6b2-3b3b-4fe1-8d55-4cc2938e0857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
