<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>0e3bad0a-31de-4757-bf30-cffe186a1efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>776c88e8-e370-4ac2-9f70-201fb93c050d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/company</value>
      <webElementGuid>e558f517-9dc7-4156-b0e6-a09c8eb4726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/company?tab=company</value>
      <webElementGuid>6d23649a-2049-46ea-97c4-562b8b2f5551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>61adadc6-d0e7-49ba-830a-e3e6cc91d53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/nav[@class=&quot;opened d-flex-ai-c animated fadeInDown navbar-header navbar-fixed-top navbar-shadow user-controlTower ng-star-inserted&quot;]/div[@class=&quot;header-items d-flex-ai-c d-flex-jc-fe&quot;]/div[@class=&quot;user-connect_items d-flex-ai-c d-flex-jc-sb&quot;]/ul[@class=&quot;navb navbar-right&quot;]/li[@class=&quot;right-menu-dropdown user-options padding-right-5-important menu-merge show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/ul[1]/li[@class=&quot;dropdown-item listElement&quot;]/a[1]</value>
      <webElementGuid>8d6349e0-f927-4b55-b71b-907808bcdf03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]/a</value>
      <webElementGuid>263866e0-03b4-43fa-92a0-df518191cd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>999a8850-323c-4610-b9e2-179b5509e754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/following::a[1]</value>
      <webElementGuid>b831f9cb-5159-4440-bb9e-436e815e2dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, My Tower'])[1]/following::a[2]</value>
      <webElementGuid>728834bc-abf9-4d10-b58d-afdb73b59cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My community'])[1]/preceding::a[1]</value>
      <webElementGuid>a7eb7819-9853-4202-995b-a4e39eeceac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[2]</value>
      <webElementGuid>f43280ee-038f-49f0-983a-14ac980dbc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>63723967-3959-4f55-9012-8e8dea05df58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/user/settings/company?tab=company')]</value>
      <webElementGuid>66d6413f-39ea-4856-9b14-ea3be66d53aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>73639137-64f9-4235-a425-9307ff3dd69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app/user/settings/company?tab=company' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>454c2548-2408-4e7d-b2f4-8ab2038d9982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
