<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SpainES</name>
   <tag></tag>
   <elementGuidId>42e65336-0ba4-4b9d-81ed-757cb521f1d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aac066def09c-205 > div.d-flex-ai-c.d-flex-jc-sb.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aac066def09c-205']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c3bf40f-d21e-47c6-904a-61a1d22b0ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex-ai-c d-flex-jc-sb ng-star-inserted</value>
      <webElementGuid>8204d6c8-b34a-4b08-8ae5-b3019217ca66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SpainES</value>
      <webElementGuid>5b3a7fe6-50d1-49c8-b587-1435f9c435a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aac066def09c-205&quot;)/div[@class=&quot;d-flex-ai-c d-flex-jc-sb ng-star-inserted&quot;]</value>
      <webElementGuid>7c13c65b-8988-48f2-9a0d-4406a0642927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>588750bf-c2e1-4b24-91f3-7ddfc740e261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex-ai-c d-flex-jc-sb ng-star-inserted</value>
      <webElementGuid>03bb61d2-4159-470d-bd56-ae9b8a5c433e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SpainES</value>
      <webElementGuid>3146ecd2-9196-48ba-ab57-6e9daff961e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aac066def09c-205&quot;)/div[@class=&quot;d-flex-ai-c d-flex-jc-sb ng-star-inserted&quot;]</value>
      <webElementGuid>d518f9a3-993e-46e2-b742-8cd713885bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07571ae3-7b05-4587-879d-3f3042a678aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex-ai-c d-flex-jc-sb ng-star-inserted</value>
      <webElementGuid>8e4f4a25-1e5b-4955-8e18-cb41beb175d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SpainES</value>
      <webElementGuid>e6395ed4-e208-4f3f-be0c-2376b2f5f440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aac066def09c-205&quot;)/div[@class=&quot;d-flex-ai-c d-flex-jc-sb ng-star-inserted&quot;]</value>
      <webElementGuid>ab5c26a3-790d-4428-8958-dd0d438654bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aac066def09c-205']/div</value>
      <webElementGuid>e4d24439-6e22-4a6e-a8ad-7b90302c5c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SS'])[1]/following::div[2]</value>
      <webElementGuid>168ed6a2-8f86-4422-8c6f-8b24d174b241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Sudan'])[1]/following::div[2]</value>
      <webElementGuid>63881da6-0ab3-4d7f-8e25-f77648baf4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[206]/div</value>
      <webElementGuid>602b9fd5-7967-4b92-ba96-1f55d74cb239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SpainES' or . = 'SpainES')]</value>
      <webElementGuid>75520d12-953e-46ce-8b66-a44b265109de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
