<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MyTower Operations</name>
   <tag></tag>
   <elementGuidId>c4e18dbf-0083-4517-b4ce-1e174801eb0b</elementGuidId>
   <imagePath>Screenshots/Targets/Page_MyTower/div_MyTower Operations.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_MyTower/div_MyTower Operations.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a2ad5eff3770-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a2ad5eff3770-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d647641d-7b62-4906-9c56-5096b3b7e605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>75d01659-99c4-45d3-8938-0e6937d6f4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1eb4f45a-0172-4a8b-8cab-05e65ff97212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a2ad5eff3770-1</value>
      <webElementGuid>5e04b377-6680-4740-9e3a-410ec1a868da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MyTower Operations</value>
      <webElementGuid>c47b31ec-1d95-403c-bf48-d55e4d8cf3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2ad5eff3770-1&quot;)</value>
      <webElementGuid>3edf9fb1-8377-4e53-8e44-7b60cead6ed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a2ad5eff3770-1']</value>
      <webElementGuid>272e0e77-1fb2-48b2-a266-bb43089e95b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a2ad5eff3770']/div/div[2]/div[2]</value>
      <webElementGuid>017a349d-b39e-4b1f-8e25-5e04b7703212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo TDC'])[1]/following::div[1]</value>
      <webElementGuid>892fc2fe-7eab-46c8-9b1f-f0d4ff671529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Establishment :'])[1]/following::div[10]</value>
      <webElementGuid>6d5bd805-c0ca-445f-98ca-5250d7cb0c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT1.1'])[1]/preceding::div[1]</value>
      <webElementGuid>2867b338-89cd-47b6-afbd-a1fb554b9908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>b6cebe69-c42c-4cd4-bd1b-aa6a4fa3f3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a2ad5eff3770-1' and (text() = 'MyTower Operations' or . = 'MyTower Operations')]</value>
      <webElementGuid>4b174374-6410-41ad-9f2e-4aaaa9c19e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
