<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AfghanistanAF</name>
   <tag></tag>
   <elementGuidId>34d02cf3-2557-4eed-a6c1-d55ca2606328</elementGuidId>
   <imagePath>Screenshots/Targets/Page_MyTower/div_AfghanistanAF.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_MyTower/div_AfghanistanAF.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex-ai-c.d-flex-jc-sb.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a2af8cf109b2-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd549378-2c6a-494a-ad6b-ae433801e1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex-ai-c d-flex-jc-sb ng-star-inserted</value>
      <webElementGuid>77f43ccc-3ede-4493-af4e-d02f88e99afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfghanistanAF</value>
      <webElementGuid>a993e762-10e3-4f89-b1a9-482369520ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2af8cf109b2-0&quot;)/div[@class=&quot;d-flex-ai-c d-flex-jc-sb ng-star-inserted&quot;]</value>
      <webElementGuid>613f91f3-5682-4304-9238-bb97e1413862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56f7a687-ebf6-4575-88f7-1175bd8720e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex-ai-c d-flex-jc-sb ng-star-inserted</value>
      <webElementGuid>14560973-5e23-4d95-b6ae-c26dd9369b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfghanistanAF</value>
      <webElementGuid>b00e6c77-102b-4235-a676-6413fe7ed018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2af8cf109b2-0&quot;)/div[@class=&quot;d-flex-ai-c d-flex-jc-sb ng-star-inserted&quot;]</value>
      <webElementGuid>1f969ed2-5fc4-400b-88ca-361b3b2192fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a2af8cf109b2-0']/div</value>
      <webElementGuid>f249e476-2e9d-4c2d-b8e8-a4f3447081ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country :'])[1]/following::div[10]</value>
      <webElementGuid>d19f91ef-c832-41fb-8478-b2223ea8e271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::div[12]</value>
      <webElementGuid>a633d6c8-035a-4b0d-9167-5bfde86c877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div</value>
      <webElementGuid>cc2148cb-6429-40da-a975-a603d815abd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AfghanistanAF' or . = 'AfghanistanAF')]</value>
      <webElementGuid>c4a8bc1c-1571-40c2-a0ae-26b7036abad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
