<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country_ng</name>
   <tag></tag>
   <elementGuidId>c3f4b3b5-3b7a-4911-b47c-da695529967f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-select[name=&quot;country&quot;] > div.ng-select-container > div.ng-value-container > div.ng-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-adresses/div/div/app-form-adresse/form/div[2]/div[7]/div/ng-select/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9332bc86-cd66-4f30-9af4-95473099378d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-input</value>
      <webElementGuid>49f77b87-ae37-4834-9574-755ffd6c70e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-adresses[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;margin-tb-10&quot;]/div[@class=&quot;form-content&quot;]/app-form-adresse[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-adress__wrapper padding-10 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-content padding-0 col-sm-12&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-xs-12 generic-inputs__style d-flex-ai-c&quot;]/div[@class=&quot;col-md-7 padding-left-0&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-invalid ng-select-focused ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]</value>
      <webElementGuid>db405bf3-1a5c-4971-8935-0eb96c9e7276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4fb449d3-18be-4ce6-99c2-1f8112aada32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-input</value>
      <webElementGuid>8b374a0e-6750-4421-8d1a-aac62ece7193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-adresses[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;margin-tb-10&quot;]/div[@class=&quot;form-content&quot;]/app-form-adresse[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-adress__wrapper padding-10 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-content padding-0 col-sm-12&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-xs-12 generic-inputs__style d-flex-ai-c&quot;]/div[@class=&quot;col-md-7 padding-left-0&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-invalid ng-select-focused ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]</value>
      <webElementGuid>5b9c3a87-f5de-47c6-b489-c7b2fbeffa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd61a738-2b83-46d2-a0d6-f1ba80e725a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-input</value>
      <webElementGuid>9fea687f-3a87-49f9-87d1-da45fafb69ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-adresses[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;margin-tb-10&quot;]/div[@class=&quot;form-content&quot;]/app-form-adresse[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-adress__wrapper padding-10 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-content padding-0 col-sm-12&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-xs-12 generic-inputs__style d-flex-ai-c&quot;]/div[@class=&quot;col-md-7 padding-left-0&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-invalid ng-select-focused ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]</value>
      <webElementGuid>d67538ad-3d17-4c66-8003-1289993e827d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-adresses/div/div/app-form-adresse/form/div[2]/div[7]/div/ng-select/div/div/div[2]</value>
      <webElementGuid>006bd54d-2398-43ed-acab-7a45dd5fe454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country :'])[1]/following::div[5]</value>
      <webElementGuid>b882af7c-478e-44c0-bc04-d558c6bf7edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::div[7]</value>
      <webElementGuid>4636f492-e2d2-429c-a46d-4efd23603733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan'])[1]/preceding::div[2]</value>
      <webElementGuid>7576437d-2f37-4f4b-a06a-423978572817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AF'])[1]/preceding::div[2]</value>
      <webElementGuid>91b8ddae-7fdc-4723-8b57-20cb111c9e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/ng-select/div/div/div[2]</value>
      <webElementGuid>31aaae2b-bc5b-4eb0-94c3-880c5af998d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
