<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Volume (m3)</name>
   <tag></tag>
   <elementGuidId>9452efac-e40a-4fa7-923a-3bf4e01bbbdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#volume</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='volume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baa0d8d8-ff02-41c3-aab4-946ebfaaf998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ui-inputtext ui-corner-all ui-state-default ui-widget</value>
      <webElementGuid>50c1e25e-925b-46b2-92e1-2b5d2860c371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>volume</value>
      <webElementGuid>f3c34119-84e2-40ad-8599-bf9d61c1c1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;volume&quot;)</value>
      <webElementGuid>9d470a53-1bef-4a82-9a85-f7b4cae97923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='volume']</value>
      <webElementGuid>98d03b20-b72f-4491-9ff0-3033a946c90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-type-units/div/app-generic-table/p-dialog/div/div[2]/div/div[7]/div[2]/input</value>
      <webElementGuid>e23419bf-b54a-49ee-bb10-8acd057d9d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>1b8ea634-bc49-465e-807f-c7c00e8da20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'volume']</value>
      <webElementGuid>e72c5de1-be53-4797-aae0-6d2d0cc0d887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
