<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type name_libelle</name>
   <tag></tag>
   <elementGuidId>e76a88da-dfab-46a0-b3c0-f4110b4337b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#libelle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='libelle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a35520c-3f2c-4fbb-9e91-9f8e55660a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ui-inputtext ui-corner-all ui-state-default ui-widget</value>
      <webElementGuid>b19b3123-92ee-4d2e-b90f-3190882bbe45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>libelle</value>
      <webElementGuid>0cbfc76c-9490-4b55-a1e2-ed65f672bcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;libelle&quot;)</value>
      <webElementGuid>4a1eec2f-6394-4eb3-8afc-16ddb05bc64d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='libelle']</value>
      <webElementGuid>e0f595b9-a230-405b-b9f1-01d307eec70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-type-units/div/app-generic-table/p-dialog/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>b0a24de2-4a51-41b2-9196-53465a69f60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>122af18e-2c98-4f59-8909-3a5ee0946f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'libelle']</value>
      <webElementGuid>314c84db-fe43-4b7e-9a0a-7d33221f9220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
