<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Owner_Of_Request</name>
   <tag></tag>
   <elementGuidId>b7c5340c-a172-4c47-acf8-73779b7452c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-option-marked ng-star-inserted&quot;][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DelrezIsabelle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3afd5f99-afa5-44c6-ac0f-62b83efa6878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-select_info</value>
      <webElementGuid>151e3411-af05-4da1-83d6-b153d795b7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DelrezIsabelle</value>
      <webElementGuid>f4f5ab8f-1c66-46ef-8e0b-e4cf5141e46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delrez Isabelle</value>
      <webElementGuid>09dcda3b-b2e6-40d8-8b6a-907cb99e4aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DelrezIsabelle&quot;)</value>
      <webElementGuid>c096ec19-ec0a-45e7-bc1e-e30629c100a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='DelrezIsabelle']</value>
      <webElementGuid>92fc15bd-5194-4ff0-8702-f462cb81ce63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='afeb52b94632-0']/div/span</value>
      <webElementGuid>3381b26a-cfa2-428a-b3b7-03155213e74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select user...'])[2]/following::span[5]</value>
      <webElementGuid>6cab3ea4-f200-4e7e-bffe-2f920a85d6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner of the request:'])[1]/following::span[5]</value>
      <webElementGuid>2da2ec82-f6c3-41ce-9aee-88fa4e87cce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mytower2018+isabelle.delrez@gmail.com'])[1]/preceding::span[1]</value>
      <webElementGuid>b8e5d4a4-d8cf-435b-9acf-63b24f4849bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From:'])[1]/preceding::span[3]</value>
      <webElementGuid>4e527020-04c6-45db-adea-5a5e9fe2644c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delrez Isabelle']/parent::*</value>
      <webElementGuid>c663503b-3aa5-49b3-a0af-379a2e8a70f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div/span</value>
      <webElementGuid>ce6c73a7-5870-4815-90d5-9715209b6a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'DelrezIsabelle' and (text() = 'Delrez Isabelle' or . = 'Delrez Isabelle')]</value>
      <webElementGuid>60b43f1f-fc09-472e-94c0-eb50583383fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
