<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>69c4083a-7b50-4e5c-ae18-10eb403c506f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='new-options__btn']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0fdedd78-fd0c-4fc6-94e5-ce31e41eb9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>3b0a6489-5ae8-4de1-8094-411cfd468a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-options__btn&quot;)/i[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>433a86a6-0592-4cc7-8e2b-cbbeb0768a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='new-options__btn']/i</value>
      <webElementGuid>276daae8-7098-48f2-bc8d-f74cc5c04049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>eee8b3cb-2124-4bf8-80a5-8421caba7d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
