<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PSL</name>
   <tag></tag>
   <elementGuidId>2727703c-5bde-476e-9a29-3d0860768b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;ui-accordion-toggle-icon pi pi-fw pi-chevron-right&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-accordion-toggle-icon.pi.pi-fw.pi-chevron-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64a2617a-8dac-4310-8eb9-8920666fa40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-accordion-toggle-icon pi pi-fw pi-chevron-right</value>
      <webElementGuid>28561e96-1d38-4c44-bccb-58f299b25fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>ui-accordion-toggle-icon</value>
      <webElementGuid>2aaa6307-152a-4bc0-bd70-f5f24fae2b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>pi pi-fw pi-chevron-right</value>
      <webElementGuid>ffa03062-2a1a-4acf-87fe-44f5c4a57f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-accordiontab-3&quot;)/span[@class=&quot;ui-accordion-toggle-icon pi pi-fw pi-chevron-right&quot;]</value>
      <webElementGuid>daed0e50-7113-4496-b7c4-6e13456c93f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-accordiontab-9']/span</value>
      <webElementGuid>b043a10d-02f8-4b82-88f7-383c4a6c50c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>d269430f-e59f-43d6-876f-c8bc0819a63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
