<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Transport_Request</name>
   <tag></tag>
   <elementGuidId>e685a854-78df-41ba-8ed5-36385da65d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;new-options__items&quot;]/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ng-star-inserted > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ddee3b7-f27d-4248-99fd-bf5dda43523e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/pricing/creation</value>
      <webElementGuid>68ee22f6-a73c-42a5-92db-0f109c61d0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/app/pricing/creation</value>
      <webElementGuid>8dbce07b-c7c3-4085-8199-72738237c9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/pricing/creation</value>
      <webElementGuid>f8e97a83-c664-49d4-8c3b-968bd8f40c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transport request</value>
      <webElementGuid>d127ae43-6f9e-4a65-9a2f-8982ba882554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-options__items&quot;)/li[@class=&quot;ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>0f695607-a917-40d1-9ac6-fe58cd323e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new-options__items']/li/a</value>
      <webElementGuid>1ffe42fc-537c-4425-9e75-c34a504830c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transport request')]</value>
      <webElementGuid>abc1c071-d8b7-4497-b2f4-9afb1458084c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select user...'])[1]/following::a[3]</value>
      <webElementGuid>02f84c13-7b18-4eb6-8ef0-f41c2ce23b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase order'])[1]/preceding::a[1]</value>
      <webElementGuid>ce9c38b5-f553-40af-bbce-2537cafff2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident'])[1]/preceding::a[2]</value>
      <webElementGuid>c90bd582-47c7-48f1-932a-9c9d497462bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transport request']/parent::*</value>
      <webElementGuid>b748247b-7b21-404e-9cff-29c213fea1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/pricing/creation')]</value>
      <webElementGuid>decaaea0-9b9d-4d8f-bcec-2bfb24fcb49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>80471ef5-f0f6-42ee-bf54-01a2aab299b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app/pricing/creation' and (text() = 'Transport request' or . = 'Transport request')]</value>
      <webElementGuid>375d48a8-0d4a-4f45-ba6b-a578909d44e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
