<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Pricing</name>
   <tag></tag>
   <elementGuidId>98012d10-174f-4c2f-8cf8-b472e642c86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[6]/app-step-pricing/div/div/div/div/div[40]/div/div[2]/p-checkbox/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p-checkbox.margin-bottom-4-important.ng-valid.ng-star-inserted.ng-dirty.ng-touched > div.ui-chkbox.ui-widget > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c607cf87-52cd-4570-8ae2-149de41b60e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-box ui-widget ui-corner-all ui-state-default</value>
      <webElementGuid>0a2cb17d-d2fb-4b77-8ea2-cb0cebf8b410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-pricing[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid relativePostion&quot;]/div[@class=&quot;row d-flex-w ng-star-inserted&quot;]/div[@class=&quot;tr_card ng-star-inserted&quot;]/div[@class=&quot;tr_card_main&quot;]/div[@class=&quot;cb_select d-flex-jc-c d-flex-w&quot;]/p-checkbox[@class=&quot;margin-bottom-4-important ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;ui-chkbox ui-widget&quot;]/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default&quot;]</value>
      <webElementGuid>e814dd4f-503b-44fd-b62d-e3d7ae2eb033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[6]/app-step-pricing/div/div/div/div/div[40]/div/div[2]/p-checkbox/div/div[2]</value>
      <webElementGuid>118a8a9d-3192-4bca-b457-3624e905f352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='carrier@nthrw.com'])[1]/following::div[7]</value>
      <webElementGuid>27bfff6b-a68b-47d0-822b-6a725709d34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User_Carrier'])[1]/following::div[7]</value>
      <webElementGuid>d2aa155e-d0b6-436b-8f1a-2eeeacd04144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[3]/preceding::div[1]</value>
      <webElementGuid>f60491b1-4341-4d01-a047-52c9134c22cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transport file'])[1]/preceding::div[4]</value>
      <webElementGuid>51d4b41b-fa5c-4484-87dd-9925863996ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[40]/div/div[2]/p-checkbox/div/div[2]</value>
      <webElementGuid>4a5426f6-7cc2-47e8-a1ed-4c9592a38754</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
