<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Road</name>
   <tag></tag>
   <elementGuidId>8040f51a-8656-4280-90ac-40752df2ccd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[5]/div/p-selectbutton/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-button.ui-widget.ui-state-default.ui-button-text-only.ng-star-inserted.ui-state-focus.ui-button-text-icon-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66159391-2271-4a64-97a6-29680b3fad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-button-text-only ng-star-inserted ui-state-focus ui-button-text-icon-left</value>
      <webElementGuid>92c6f90c-2fd6-455b-99a2-3f2affae2a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-d</value>
      <webElementGuid>ad579244-88a4-4a36-accc-ed86dec52e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>0cf5621b-45a3-4c1d-af56-b95a73f93df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Road</value>
      <webElementGuid>87fee21a-3dae-468d-bd5e-aa556046fa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>666d4b72-e172-41cc-bb6d-dbd46741225c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Road</value>
      <webElementGuid>7191dc50-b3b1-4a79-bfea-f1a069d6302d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 col-xs-12 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8&quot;]/p-selectbutton[@class=&quot;mode-transport__buttons col-md-12 padding-0 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ui-selectbutton ui-buttonset ui-widget ui-corner-all ui-buttonset-5&quot;]/div[@class=&quot;ui-button ui-widget ui-state-default ui-button-text-only ng-star-inserted ui-state-focus ui-button-text-icon-left&quot;]</value>
      <webElementGuid>26fb7edf-08d4-45c1-846d-2f21a0a928f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[5]/div/p-selectbutton/div/div[3]</value>
      <webElementGuid>2133d998-4ef4-43ef-9615-4156f490e4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sea'])[1]/following::div[1]</value>
      <webElementGuid>26af8824-cd87-481a-8523-a238efda4a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Air'])[1]/following::div[2]</value>
      <webElementGuid>3b1205f9-9d9f-4e83-a075-5c4f103550f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rail'])[1]/preceding::div[1]</value>
      <webElementGuid>16fe4c98-56da-48c8-a74a-132bed6b8569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-selectbutton/div/div[3]</value>
      <webElementGuid>3a324fb9-7e0e-4275-8e77-1b23fd917dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Road' or . = 'Road')]</value>
      <webElementGuid>6105355d-06fd-49cc-af02-c973780c8dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
