<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_Service_Level</name>
   <tag></tag>
   <elementGuidId>e51d6a73-04e8-43e2-8ef1-a7d69145feff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;typeRequestselect&quot;]/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8ae5c5b9-99ec-472a-8dd5-91273cfbbd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1659015741923</value>
      <webElementGuid>155a2d0c-3923-4478-b3ee-db8ad0a03d91</webElementGuid>
   </webElementProperties>
</WebElementEntity>
