<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_Of_Goods_Availability</name>
   <tag></tag>
   <elementGuidId>bf52be4a-fa16-4b31-b9e8-3877ed153ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div[1]/div/div[2]/app-step-expedition/div/div[1]/div[2]/div[1]/div/app-datetime-picker/div[1]/div[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.date-picker-input.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55db8d0c-f529-4762-b533-ea894f8dac5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1754844f-ac08-4a93-833a-0ef121a485b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>e39242b1-21bf-4e5f-af0b-bed7323fd0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>d89aadda-7fd7-4913-976b-e01dba7b6baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5855ecec-b55c-439b-8a32-05fb8674d101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>9308ed61-bd67-4dea-bcd6-cf804b5f66f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3bfe58ef-2e7e-4d29-86dc-cbd43f7ee926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>demande.dateOfGoodsAvailabilit</value>
      <webElementGuid>fd972d72-c627-48a1-b8de-32b6a2abbda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a612397-ce01-478d-84f7-56e440f7cde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 margin-top-15 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 padding-right-0&quot;]/app-datetime-picker[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;col-md-12 nopadding date-picker_wrapper&quot;]/div[@class=&quot;col-md-8 padding-left-0 padding-right-5&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control date-picker-input ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>565f7045-8be0-4996-8085-1b0d38d4af20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div[2]/div/div/app-datetime-picker/div/div/div/input</value>
      <webElementGuid>cb9092e1-54af-4866-bccf-717473ffd631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-datetime-picker/div/div/div/input</value>
      <webElementGuid>c7ca47d7-f558-4e3f-ae6f-b93122a18b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>6a5b8ee0-849f-4381-a51d-72c0f887fc79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
