<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Service_Level</name>
   <tag></tag>
   <elementGuidId>861e44cc-42ea-4ee9-bf20-7ee99ceed4d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='typeRequestselect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typeRequestselect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d864b250-7731-4eed-a20a-4bf321430683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>b5603f93-0b24-497e-8e89-85f5238e7c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeRequestselect</value>
      <webElementGuid>2f28e399-2c87-4413-9f1a-72c41227ef72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeRequestselect</value>
      <webElementGuid>70f222fc-0713-4594-b96a-3cc576992b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>typeRequestselect</value>
      <webElementGuid>cffc143c-44d2-4ac5-bee2-3025e13034df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0556749-f654-4f0e-8567-136498a426e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> URG-Urgent  STD-Standard </value>
      <webElementGuid>f3e85d03-f740-43d9-80fd-3cf0fccaa45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeRequestselect&quot;)</value>
      <webElementGuid>2550fe79-c5ea-41f0-91f4-aa0235bd7f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='typeRequestselect']</value>
      <webElementGuid>cb627438-35c5-41da-b716-c7fe8175b4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[3]/app-step-reference/div/div/form/div[2]/div/fieldset/div/div/select</value>
      <webElementGuid>904ecd6d-490b-4e89-b431-957a2e2e62a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service level:'])[1]/following::select[1]</value>
      <webElementGuid>ae7c4304-b066-425d-8e6c-bd6a171dc206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a cost center ...'])[1]/following::select[1]</value>
      <webElementGuid>c725a2e2-15e5-43f4-b3c4-2dc1fd37daba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[1]/preceding::select[1]</value>
      <webElementGuid>5c17dc46-f290-4c08-883b-d2e0ae692aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice currency'])[1]/preceding::select[1]</value>
      <webElementGuid>753999c2-bf2e-4b61-88d3-b87a2b9a2245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/select</value>
      <webElementGuid>9d321977-9c38-4934-88ba-2a175f2a6fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'typeRequestselect' and @name = 'typeRequestselect' and (text() = ' URG-Urgent  STD-Standard ' or . = ' URG-Urgent  STD-Standard ')]</value>
      <webElementGuid>c1d67983-28ce-4c7f-a026-12c67ea617d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
