<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Incoterm</name>
   <tag></tag>
   <elementGuidId>3a72606a-53c7-478f-b9a3-184e793beb86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='incoterms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;incoterms&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af9de309-f7c4-4400-adf7-ef6aea319119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>34468cde-3098-4bdf-86dc-0963167482e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>incoterms</value>
      <webElementGuid>474b09fa-4557-4ea1-9a7f-d595f164f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-compare-with</name>
      <type>Main</type>
      <value>function (val1, val2) {
      </value>
      <webElementGuid>9d51d0f2-2e24-4389-8188-9285fdc6c48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>incoterms</value>
      <webElementGuid>40e59b61-2865-4af0-b192-4335ae8a1fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8266da14-2f3e-4571-8916-382ab7d5f7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>6fb490e6-ac5b-4ab5-80b1-f0219cf5b518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CFR  CIF  CIP  CPT  DAP  DAT  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  FAS  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) </value>
      <webElementGuid>203dc5c3-9668-4c1c-a07f-bbe67b9bb9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 d-flex-ai-fe generic-inputs__style&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-xs-12 padding-right-0 input-wrapper padding-0&quot;]/select[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>b55b3840-c51f-4a1c-9f57-7c90ae53e812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='incoterms']</value>
      <webElementGuid>b35aa640-17d1-45f4-bd64-7816e0e1fea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[10]/div/select</value>
      <webElementGuid>07eb1d7c-56c3-4b02-94c2-3b7e77d087b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoterm:'])[1]/following::select[1]</value>
      <webElementGuid>b13e6832-9cc9-4e53-b903-4ee8dbd815f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/following::select[1]</value>
      <webElementGuid>ad4da258-f9ac-45ae-81fc-4e263a3d2255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of goods availability:'])[1]/preceding::select[1]</value>
      <webElementGuid>67c3f5aa-f238-4f5b-aba3-3853e671e4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of arrival:'])[1]/preceding::select[1]</value>
      <webElementGuid>76bfdb85-b409-4bed-ae83-ea5a5f69b8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>9cdf116c-60fe-4cd2-bcc6-049999eb925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'incoterms' and (text() = ' CFR  CIF  CIP  CPT  DAP  DAT  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  FAS  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) ' or . = ' CFR  CIF  CIP  CPT  DAP  DAT  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  FAS  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) ')]</value>
      <webElementGuid>3831f4c3-4ba6-46fc-b973-199619611952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
