<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Flux_Transport</name>
   <tag></tag>
   <elementGuidId>2f59ca1b-f00e-4fee-a3a3-cee98f2c9999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='typeFlux']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;typeFlux&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edbc2798-edcc-4d54-8eff-bb96da04c83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-star-inserted ng-valid ng-touched</value>
      <webElementGuid>65dd813c-0992-4e4a-92e5-2878a4f9211e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeFlux</value>
      <webElementGuid>1a3787d2-75f7-40df-ad67-0424b8f23c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-compare-with</name>
      <type>Main</type>
      <value>function (val1, val2) {
      </value>
      <webElementGuid>cf6f5151-a020-4e9a-b74d-86f98248a656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>typeFlux</value>
      <webElementGuid>0c1b3d2d-3fc6-4c4e-943c-27e546855106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c7dd761-5f9f-4296-bcc7-631e46de8835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>38bcd7e6-8655-47b3-9c2a-36dc8de7b97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Flux transport </value>
      <webElementGuid>6c47622f-dd65-4e5b-801a-03cb66002328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 d-flex-ai-fe generic-inputs__style ng-star-inserted&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 padding-right-0 input-wrapper&quot;]/div[@class=&quot;ng-star-inserted&quot;]/select[@class=&quot;form-control ng-pristine ng-star-inserted ng-valid ng-touched&quot;]</value>
      <webElementGuid>ca35bee7-6d8d-4fc0-bbc9-7a1e6c6b1e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='typeFlux']</value>
      <webElementGuid>aed72ba8-0b54-457b-a7ca-1e10f7b50568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[8]/div/div/select</value>
      <webElementGuid>409fc215-777d-49c4-bcae-e5f34706ecdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of flow'])[1]/following::select[1]</value>
      <webElementGuid>5f9c9d24-ac4f-4141-b9bd-31d9cd05c64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSL Schema:'])[1]/preceding::select[1]</value>
      <webElementGuid>6faf1f04-d904-4892-a651-8221e1bf5fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoterm:'])[1]/preceding::select[2]</value>
      <webElementGuid>671c376b-8830-4930-b534-1d3bb594cea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1cfaa961-7a89-4d09-8e76-c2397b1cdc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'typeFlux' and (text() = ' Flux transport ' or . = ' Flux transport ')]</value>
      <webElementGuid>00cfa380-7805-46c9-b24f-c15252c680d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
