<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PSL_Schema</name>
   <tag></tag>
   <elementGuidId>1166b246-4c9c-4998-bfd2-06346864ff4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ebSchemaPSl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ebSchemaPSl&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9af9357f-502f-428b-8fda-86d6fab10582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>8554ac86-6bc3-4d13-a62e-adb163ad5bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ebSchemaPSl</value>
      <webElementGuid>dc0fd543-9cd3-4f58-99d6-ede6ab3242a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-compare-with</name>
      <type>Main</type>
      <value>function (val1, val2) {
      </value>
      <webElementGuid>f50b2d8a-604e-4e57-8738-babaf85f8044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>ebSchemaPSl</value>
      <webElementGuid>973c96f1-a59b-4bb0-a45b-b8205f93d359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25954bc5-933f-4053-9caa-20486068faeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CFR  CIF  CIP  CPT  CPT  DAP  DAP  DAT  DDP  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  EXW (Import DAP)  FAS  FCA  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) </value>
      <webElementGuid>9084852f-2e2c-4666-94b0-2890763ed89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-demande-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-expedition[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content col-md-12&quot;]/div[@class=&quot;section row margin-right--14&quot;]/div[@class=&quot;col-md-12 generic-inputs__style ng-star-inserted&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 padding-right-0 input-wrapper&quot;]/div[1]/select[@class=&quot;form-control ng-pristine ng-invalid ng-touched&quot;]</value>
      <webElementGuid>3cb7d2fc-502a-45c7-a676-8c0f23fadd78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ebSchemaPSl']</value>
      <webElementGuid>436b357d-57d8-49d3-bae5-999ad1a3a935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-creation/div/div/div[2]/app-demande-creation-form/div/div[2]/div/div/div[2]/app-step-expedition/div/div/div/div[9]/div/div/select</value>
      <webElementGuid>6f77472f-0427-4128-bfb9-8669252323e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSL Schema:'])[1]/following::select[1]</value>
      <webElementGuid>4931f361-9c58-4268-ae3d-23f9aa7bd983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of flow'])[1]/following::select[2]</value>
      <webElementGuid>521895df-3ffa-46d2-8c37-936efc2c6c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/preceding::select[1]</value>
      <webElementGuid>33d178f9-c04d-43a7-87d4-333f46868d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoterm:'])[1]/preceding::select[1]</value>
      <webElementGuid>3b8ed4a2-b40f-46f9-97f3-1681bf588574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>742222d3-08e0-48d2-8eb4-e1ce08e2f053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ebSchemaPSl' and (text() = ' CFR  CIF  CIP  CPT  CPT  DAP  DAP  DAT  DDP  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  EXW (Import DAP)  FAS  FCA  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) ' or . = ' CFR  CIF  CIP  CPT  CPT  DAP  DAP  DAT  DDP  DDP  EXW (Export DAP)  EXW (Export)  EXW (Import CPT/CFR)  EXW (Import DAP)  EXW (Import DAP)  FAS  FCA  FCA  FOB (Export)  FOB (Import DAP)  FOB (Import DDP) ')]</value>
      <webElementGuid>d9410ef7-b270-41e2-bc67-6528503337c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
