<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bell</name>
   <tag></tag>
   <elementGuidId>0a3f4ce5-dcac-4359-b785-ae841dc6668b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbar-notifs_btn']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0f8506db-24a1-4d9a-b66d-c4f5cd1d7b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bell</value>
      <webElementGuid>14053333-b0f4-494f-aeec-8f4820f586a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>e562f584-fe54-4229-908c-d3846ab44e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-notifs_btn&quot;)/i[@class=&quot;fa fa-bell&quot;]</value>
      <webElementGuid>211dd7b3-e0a9-4831-b06f-331d1195d673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbar-notifs_btn']/i</value>
      <webElementGuid>f3ba9608-5f3c-4260-89e4-459311d37eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>0695e580-92cf-427c-8aa8-95020ed0c730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Notifications']</value>
      <webElementGuid>4b678879-c9d6-4a86-93a8-8246deceb936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
