<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit_Quotation</name>
   <tag></tag>
   <elementGuidId>8631589b-0a49-47fa-a82e-1cb68cce6b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div[3]/div/div/div/div[2]/app-cotation/div/div/div/div/button[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-sm.ng-star-inserted > span > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>415871a3-2e82-4431-8b6a-c73144eeff25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>3adccff5-1f97-4526-bbcf-6ca132166af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Submit quotation </value>
      <webElementGuid>f0a278aa-380f-4c35-aafc-8adb737394fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-visualisation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper col-md-12 padding-0&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;new-design_details-contents col-md-12 padding-0&quot;]/div[@class=&quot;collapsible-blocs&quot;]/div[@class=&quot;middle-blocs col-md-6 col-sm-12 col-xs-12 padding-4&quot;]/app-demande-creation-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;create-wf-root form-card-no-border&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-pricing[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;modal modal-backdrop show ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/div[@class=&quot;modal-body&quot;]/app-cotation[1]/div[@class=&quot;d-flex col-md-12 padding-0 cotation-app__wrapper&quot;]/div[@class=&quot;padding-left-0 col-md-12&quot;]/div[@class=&quot;row margin-top-20-important&quot;]/div[@class=&quot;text-right&quot;]/button[@class=&quot;btn btn-primary btn-sm ng-star-inserted&quot;]/span[1]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>c06439f2-4030-48d2-b82e-52dad3d4e0f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div[3]/div/div/div/div[2]/app-cotation/div/div/div/div/button[2]/span/span</value>
      <webElementGuid>13e5905a-d8d9-4836-af43-135cbf8bb52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>551cf360-4013-41d8-9abe-b17c830ef293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::span[2]</value>
      <webElementGuid>dd35155c-a602-4495-806c-f38690a39095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Carrier', &quot;'&quot;, 's unique Ref number:')])[1]/preceding::span[1]</value>
      <webElementGuid>047fedfd-65d3-47d4-bd4e-1c5e0d8a9350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° AWB/BOL:'])[1]/preceding::span[1]</value>
      <webElementGuid>03daa595-7ac3-4c72-a8ba-4c205359463c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit quotation']/parent::*</value>
      <webElementGuid>57e6debe-43c8-4e57-8362-13200293d365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>22b77992-7d10-4727-9c1a-ad9cc99ade98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Submit quotation ' or . = ' Submit quotation ')]</value>
      <webElementGuid>4a57c036-6a85-489d-ba7d-284b936e4c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
