<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pricing</name>
   <tag></tag>
   <elementGuidId>ad86bc0d-69c9-4239-a988-bbc097fe3364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-accordiontab-4']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-accordion-header-text.ng-tns-c24-5.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4d9a1db-99f6-4676-8f81-39ce70019185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-accordion-header-text ng-tns-c24-5 ng-star-inserted</value>
      <webElementGuid>f2521ba0-eedd-4882-b665-fcce311a241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pricing </value>
      <webElementGuid>405078c5-a718-4609-8144-8ef02d0965f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-accordiontab-4&quot;)/span[@class=&quot;ui-accordion-header-text ng-tns-c24-5 ng-star-inserted&quot;]</value>
      <webElementGuid>d3752959-9f1c-4114-ba30-215cc5b41692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-accordiontab-4']/span[2]</value>
      <webElementGuid>6c457909-b108-4bc6-a8b0-181870a3f4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of units:'])[1]/following::span[3]</value>
      <webElementGuid>fd04e649-5536-4616-83f4-e0d7a9b8cfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles Overview'])[1]/following::span[3]</value>
      <webElementGuid>747cc1da-becc-4936-a212-083384459b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request sent:'])[1]/preceding::span[1]</value>
      <webElementGuid>9b90e5f9-a052-4b6b-acfc-301a5806fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner of the request:'])[1]/preceding::span[2]</value>
      <webElementGuid>b76e3f17-c4e9-49cf-acdc-176316aea090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-accordiontab[4]/div/a/span[2]</value>
      <webElementGuid>a2fbce45-a332-4756-a243-2336241314c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Pricing ' or . = ' Pricing ')]</value>
      <webElementGuid>90be72bd-98bb-4d70-945b-6310a6d9130d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
