<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_Price</name>
   <tag></tag>
   <elementGuidId>be15bff8-bb7f-4625-8c42-7a6c87f0ef72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4566d439-c5c0-45d0-89d4-e6ada2866dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center date-picker-input form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d3f7c1f9-d177-4f02-a43b-d63755aa548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>2748ace0-aa45-45bd-9603-00acbc9c5ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exEbDemandeTransporteur.price</value>
      <webElementGuid>81fc636d-8fd0-4aa5-8de6-0725e1d2b17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>661fb32c-4a28-45ce-a2a4-ee22c62e0e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price&quot;)</value>
      <webElementGuid>94c7ce46-bc81-47c1-91e0-349dac99857f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='price']</value>
      <webElementGuid>1f5a719c-7a6a-4e12-a03e-844d7f408bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div[3]/div/div/div/div[2]/app-cotation/div/div/form/fieldset/div/div[2]/div/fieldset/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3fe14daf-1f05-437a-875a-513457f28f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>531aa94e-174c-4338-9de1-5404b7c678b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'price' and @name = 'exEbDemandeTransporteur.price' and @type = 'number']</value>
      <webElementGuid>1c3a8c83-9e0d-43ce-a95c-d6c86c46e5bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
