<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total transit time</name>
   <tag></tag>
   <elementGuidId>80bd2634-335d-4ad3-9fe9-26f4ca0dbd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transitTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transitTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bac0a0b-1f73-4ee8-8676-852749b73706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f6850369-23af-40d3-8d3b-d1a66eb65fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transitTime</value>
      <webElementGuid>06015845-030d-4398-9228-f2bed2a2b10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1d9439f-3329-4d82-b169-44d31a521768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exEbDemandeTransporteur.transitTime</value>
      <webElementGuid>4a7a1768-c81e-4311-8dd4-d29118a62017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>054021ef-0e80-43e7-b273-1bf5001f3e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitTime&quot;)</value>
      <webElementGuid>0ab27544-940e-4c6b-9742-5de8e7fc5641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transitTime']</value>
      <webElementGuid>33f4c764-a682-4ba3-a374-fc9c1ae0f13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div/div/div[2]/app-demande-creation-form/div/div/div/div/div[6]/app-step-pricing/div/div[3]/div/div/div/div[2]/app-cotation/div/div/form/fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>c45c9a45-3ce7-445c-93d4-79edc50e24e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>24e5ebf5-2c8e-4c19-bd81-8d2c7b0086d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transitTime' and @name = 'exEbDemandeTransporteur.transitTime' and @type = 'number']</value>
      <webElementGuid>19d7ec8e-707f-4337-8823-e86a11af89b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
