<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_From</name>
   <tag></tag>
   <elementGuidId>7bffe741-18d3-43ec-8c8e-9c097aacc517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a27f4b50a1fe-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-star-inserted&quot;][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5acdd88-3c24-40b1-851d-19116d3cd4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>596e7fed-d764-4f76-b1cd-776752ac658b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>33857bdf-ca93-4124-a7d6-d7bf6f780e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a27f4b50a1fe-5</value>
      <webElementGuid>1ab85035-c382-4dd4-aa5a-fda5bf8098d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARS - Argentine peso</value>
      <webElementGuid>678e819f-a354-4e14-adfe-ea1fd6daf267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a27f4b50a1fe-5&quot;)</value>
      <webElementGuid>67f13532-12fd-45e0-b145-17d38c8dba86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a27f4b50a1fe-5']</value>
      <webElementGuid>e786d3c8-a7a6-42ff-8f8c-e1724287b8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a27f4b50a1fe']/div/div[2]/div[6]</value>
      <webElementGuid>e37c9304-7327-4b62-9ea3-eb7860f78435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOA - Angolan kwanza'])[1]/following::div[1]</value>
      <webElementGuid>d6fa57ac-4fb1-411f-ba19-b49c2a5e3608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANG - Netherlands Antillean guilder'])[1]/following::div[2]</value>
      <webElementGuid>b925ad4c-a444-4955-8d92-c96e262438fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHP - Philippine piso'])[1]/preceding::div[1]</value>
      <webElementGuid>bd9a0fdb-1d29-491e-898c-63954d56d43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]</value>
      <webElementGuid>143bb3d5-51d2-4aa8-b84a-c42757309ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a27f4b50a1fe-5' and (text() = 'ARS - Argentine peso' or . = 'ARS - Argentine peso')]</value>
      <webElementGuid>05f28965-af24-4223-8d3a-0fccb23480c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
