<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carrier</name>
   <tag></tag>
   <elementGuidId>290ccc4e-d9bf-4411-b76e-ed6e0440ba02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a37bc30ebfd3-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-star-inserted&quot;][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7a04de0-226c-4024-b4f3-e7bdacb431c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>23bebc33-aca4-416c-9869-fb507bcf4eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6800586d-06b0-4d08-b5d4-a5f4056ba4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a37bc30ebfd3-0</value>
      <webElementGuid>372184a8-5ee3-4789-969c-b1e144db0ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DT PROJECT</value>
      <webElementGuid>a3804346-fecc-4517-8d0d-e20b551f0d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a37bc30ebfd3-0&quot;)</value>
      <webElementGuid>ca3e1a76-16b2-4da9-aa7b-e671fc8b89db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a37bc30ebfd3-0']</value>
      <webElementGuid>37d3c175-9e6b-489e-9325-b8bf565f198c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a37bc30ebfd3']/div/div[2]/div</value>
      <webElementGuid>97b82466-66d0-47f2-aae9-6bed97061be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select compagnie'])[2]/following::div[5]</value>
      <webElementGuid>242fa97c-318b-41a5-b2f5-4032033023a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrier'])[1]/following::div[9]</value>
      <webElementGuid>e991e4fa-2b84-4d77-b6fe-e944922bf18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERLINES'])[1]/preceding::div[1]</value>
      <webElementGuid>d918217f-03c5-447f-ae28-f986d1810ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>93f48a47-4aa3-4704-8400-0051efeb2c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a37bc30ebfd3-0' and (text() = 'DT PROJECT' or . = 'DT PROJECT')]</value>
      <webElementGuid>f98eed40-d481-40b6-84b4-d9231a3b871c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
