<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beginning_Date</name>
   <tag></tag>
   <elementGuidId>b1dacd3b-f45d-4263-8bd5-93c3437eb903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.date-picker-input.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-datetime-picker[@id='dateDebut']/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45dbd435-b359-48b0-aa91-b18b8e188e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>39f105a4-4e8e-49d6-bd1a-7ce00d2b1eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>ce5c4d13-da5d-4170-ad6f-ed10c3e506eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>6116f7d7-b122-4b25-82bc-05a943bd9fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateDebut&quot;)/div[@class=&quot;col-md-12 nopadding date-picker_wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control date-picker-input ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>84f10923-18e8-4e48-a158-4046a9a81cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-datetime-picker[@id='dateDebut']/div/div/div/input</value>
      <webElementGuid>d5f9bfde-ecfe-458a-8df9-98756c141ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-datetime-picker/div/div/div/input</value>
      <webElementGuid>5e6bd10c-55bc-4617-aeec-69cc43bfe21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>e098504d-3f4d-458b-ac94-8c770e527337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
