<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CountryEdit</name>
   <tag></tag>
   <elementGuidId>d8ec542a-af78-4289-9381-915695eb4047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a26ac33bfb49-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-star-inserted&quot;][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61ca96fb-25ee-42d0-8dfd-908c39b5ecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>a1895e51-3eb0-4b57-9216-c1e62c608084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9af34364-98d4-412a-8a35-967e1e0bf40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a26ac33bfb49-0</value>
      <webElementGuid>96e97cca-7e8a-486f-ad68-ae7f9cfb69c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfghanistanAF</value>
      <webElementGuid>5f20a594-826d-4680-8229-2466e0ad2d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a26ac33bfb49-0&quot;)</value>
      <webElementGuid>216abd2a-2c8d-42e1-b68f-3544ada3ec24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a26ac33bfb49-0']</value>
      <webElementGuid>b4ce1dde-dd63-4649-a70b-74580b05c045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a26ac33bfb49']/div/div[2]/div</value>
      <webElementGuid>e7a117be-a1e6-410c-961c-91687f6ce867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country :'])[1]/following::div[9]</value>
      <webElementGuid>a9b1e2f0-808d-4e68-96d0-07df8d67130d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::div[11]</value>
      <webElementGuid>3d414f04-9116-4ffd-ba90-efa5372f929d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>b8f44b40-10fa-414e-800b-4539d2765590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a26ac33bfb49-0' and (text() = 'AfghanistanAF' or . = 'AfghanistanAF')]</value>
      <webElementGuid>6e4bd3ac-b025-4471-acb3-366a98b3b11c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
