<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Etablishment</name>
   <tag></tag>
   <elementGuidId>a52b8876-7ae6-48b9-b71b-68b435de2d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a0c5ae1671da-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-star-inserted&quot;][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>304963b4-de3f-483d-800d-8471d6d8ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>9b54c154-784e-40c1-9f4a-bf8114402b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>90e31693-0d33-4a6a-b3a5-433fdb4e02ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a0c5ae1671da-3</value>
      <webElementGuid>c9cefdc0-b33e-47d8-9f38-47aaa204c655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quotation Desk (EXN)</value>
      <webElementGuid>cb71195d-2b00-4ca1-b668-1be195e9f809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a0c5ae1671da-3&quot;)</value>
      <webElementGuid>ab743ba2-4fb4-41e1-ba9e-23bb60fb8d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a0c5ae1671da-3']</value>
      <webElementGuid>afbb3a69-6578-4177-b862-a33f9959da14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a0c5ae1671da']/div/div[2]/div[4]</value>
      <webElementGuid>3fd520cd-7967-4e5d-b794-949b18817ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT1.1'])[1]/following::div[1]</value>
      <webElementGuid>587e91a3-ba82-468d-b28c-41224c0ee250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyTower Operations'])[1]/following::div[2]</value>
      <webElementGuid>94cc05da-8ded-4111-abed-0105e41aceb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT1.2'])[1]/preceding::div[1]</value>
      <webElementGuid>f184ffcd-8647-49e4-8e66-608b6393482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]</value>
      <webElementGuid>378c4ede-9177-4d56-b566-f79d8b9b0ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a0c5ae1671da-3' and (text() = 'Quotation Desk (EXN)' or . = 'Quotation Desk (EXN)')]</value>
      <webElementGuid>c25825f3-3769-4de1-9ae6-ece2650a52ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
