<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country</name>
   <tag></tag>
   <elementGuidId>60a516aa-f249-43ce-a512-f992b404abb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a26ac33bfb49-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;ng-option ng-star-inserted&quot;][46]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cabfa1b-10e0-47c1-9a8f-718162cce72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>8cef9c67-83f5-4200-afdc-683b1061a49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e582f9ba-77d8-4b2e-a879-9f53c402c6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a26ac33bfb49-0</value>
      <webElementGuid>33c82f64-2af2-4c79-a3b5-0adde661c223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfghanistanAF</value>
      <webElementGuid>746c3db6-a5ea-473b-9151-92e43af2e8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a26ac33bfb49-0&quot;)</value>
      <webElementGuid>3c1f7ded-7e26-4aa5-94c5-4830c41930f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a26ac33bfb49-0']</value>
      <webElementGuid>81e91754-350e-4e5c-a6f1-4adbdccef8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a26ac33bfb49']/div/div[2]/div</value>
      <webElementGuid>a3974473-ac00-4c2a-8416-a60264433bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country :'])[1]/following::div[9]</value>
      <webElementGuid>279704df-1611-47b7-aec8-86a8d5d24324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::div[11]</value>
      <webElementGuid>84793d6d-a50c-4bfa-9771-8834acf9693b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>d651ae9a-2af0-4bf5-be7f-eb5eeda35d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a26ac33bfb49-0' and (text() = 'AfghanistanAF' or . = 'AfghanistanAF')]</value>
      <webElementGuid>3f2d6365-e0cc-4c1c-b901-e537a93ad67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
