<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Details</name>
   <tag></tag>
   <elementGuidId>7565827e-e2be-47f7-af4f-88f77ecff9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Details' or . = 'Details')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55df3434-32c1-418c-b503-ad64a4d2ca13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs</value>
      <webElementGuid>3b8ec530-ddd8-4875-b86a-a288de066c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8edadfd-cf48-40b8-9999-fd2a491d05d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.functions.showDetailsPrice(23457,14642)</value>
      <webElementGuid>a284048d-9690-48db-a80b-2d4f2e84ad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>406b5541-1f31-45ba-a168-ba0610b41e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/p-table[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ui-table ui-widget ui-table-resizable ui-table-resizable-fit&quot;]/div[@class=&quot;ui-table-scrollable-wrapper ng-star-inserted&quot;]/div[@class=&quot;ui-table-scrollable-view&quot;]/div[@class=&quot;ui-table-scrollable-body&quot;]/table[@class=&quot;ui-table-scrollable-body-table&quot;]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;textCenter colonne-generic-table gtbl-td ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;btn btn-primary btn-xs&quot;]</value>
      <webElementGuid>cd030ee5-3c64-4262-949a-67648f153511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;ui-panel-0-content&quot;]/div/p-table/div/div[1]/div/div[2]/table/tbody/tr[1]/td[29]</value>
      <webElementGuid>ec44a91c-696f-4586-89c2-54193e34aa23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/p-table/div/div/div/div[2]/table/tbody/tr/td[29]/span/span/div</value>
      <webElementGuid>9f71aee8-7175-4d72-8f27-e22065be194f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doc &amp; His'])[1]/following::div[1]</value>
      <webElementGuid>2610ca2c-2cfb-4dab-844e-876e3545ab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR -> Euro : 1'])[1]/preceding::div[1]</value>
      <webElementGuid>0dee6ba6-7590-4ab9-8ac2-b368f40d7613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSY-A23455'])[1]/preceding::div[12]</value>
      <webElementGuid>88fc182a-df1a-4652-9620-ed18fab4a36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[29]/span/span/div</value>
      <webElementGuid>f9c1a1e4-16a4-4f70-8217-dca256096be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Details' or . = 'Details')]</value>
      <webElementGuid>2296f322-6e37-4246-b640-c16a9b133ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
