<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Freight_Audit</name>
   <tag></tag>
   <elementGuidId>5931cc92-ac3c-4e9d-ab73-c77d250fe6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.my-icon-freight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(@class,&quot;my-icon-freight&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1623cd8f-5f23-4c89-ae44-80a565181b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-icon-freight</value>
      <webElementGuid>212df906-c8c5-467d-821c-87d19da10be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-wrapper__items&quot;)/li[@class=&quot;border-bottom_trans ng-star-inserted&quot;]/a[1]/span[@class=&quot;my-icon-freight&quot;]</value>
      <webElementGuid>d305d124-1bf3-4497-a619-374f164120ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[contains(@class,&quot;my-icon-freight&quot;)]</value>
      <webElementGuid>de84d0a2-fc69-43be-991d-3b3cc64cf38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>f9eb2fc8-f4d7-4daa-93c0-57b678832b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
