<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Purchase_Order</name>
   <tag></tag>
   <elementGuidId>9cd0042b-465b-45bc-8888-16b2911e1ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='new-options__items']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>529342a8-6738-4983-b089-2727c4ac76c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>app/delivery-overview/order/creation</value>
      <webElementGuid>2b0150b9-24fa-46e1-ba4c-51c200039cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/delivery-overview/order/creation</value>
      <webElementGuid>8788739d-c484-4301-8cdd-bda56129c534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase order</value>
      <webElementGuid>e7c9bf6b-70fd-4227-a90e-0ba251ca756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-options__items&quot;)/li[@class=&quot;ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>b0ea3d40-ba0c-4cb8-84c7-3b7e5a5b4d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new-options__items']/li[2]/a</value>
      <webElementGuid>7a2be3d4-e5a1-4202-b7db-046b68c0d55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Purchase order')]</value>
      <webElementGuid>08e8a905-2f33-499b-8a2b-6a72fe156a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transport request'])[1]/following::a[1]</value>
      <webElementGuid>70127103-af6a-4558-af61-f69b5a4cd402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/preceding::a[2]</value>
      <webElementGuid>e93d02a5-ffe9-40e8-8a7f-00f50a3d2ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase order']/parent::*</value>
      <webElementGuid>35798856-e0f9-4325-a183-c005f44b1075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/delivery-overview/order/creation')]</value>
      <webElementGuid>e0b04cb8-cbd0-4dde-846e-a8d2a6b95a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>e671b8da-9443-49a1-93a1-1f7717da589f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app/delivery-overview/order/creation' and (text() = 'Purchase order' or . = 'Purchase order')]</value>
      <webElementGuid>7154e57d-81c5-41c1-9629-5047373917eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
