<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sold_To</name>
   <tag></tag>
   <elementGuidId>49d40ed1-936f-4444-b3e3-90cc67e22bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-order-creation/div/div/div[2]/app-order-creation-form/div/div[2]/div[1]/div/div[1]/app-order-step-order/div/div[1]/div[1]/div[5]/app-adresse-for-shipping-order/fieldset/div/div/div/div[1]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>795397ac-5555-454d-98d3-d933594acd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96eb5078-ecf9-4ad4-9e65-8019a09ade18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed0304f8-ae3c-48cd-8527-6f84dd1a8104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-order-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-order-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-order-step-order[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;section&quot;]/div[@class=&quot;col-md-12 col-xs-12&quot;]/app-adresse-for-shipping-order[1]/fieldset[@class=&quot;border-0 margin-0-important&quot;]/div[@class=&quot;adress-wrapper&quot;]/div[@class=&quot;fields-wrapper&quot;]/div[@class=&quot;show-for-creation clearfix&quot;]/div[@class=&quot;col-md-12 padding-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8 col-xs-12 padding-right-0 input-wrapper&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>cafd7fb1-dcf4-4fdf-82c5-9c845d0f454f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>74ca2f65-e28b-4744-927e-1dcc921481ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-order-creation/div/div/div[2]/app-order-creation-form/div/div[2]/div/div/div/app-order-step-order/div/div/div/div[4]/app-adresse-for-shipping-order/fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>f3313d3e-8d4f-43c0-b763-a4aef1972b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-adresse-for-shipping-order/fieldset/div/div/div/div/div/div/input</value>
      <webElementGuid>eba1d3f8-2903-4235-9de3-9df9666851fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>24170dbb-02a5-4ab6-bc24-bcb005bd2a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
