<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item_Number</name>
   <tag></tag>
   <elementGuidId>4ab68dd4-d7fd-48de-92dc-e5dfdb7cb2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-show-onhover.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-1-content']/div/p-table/div/div/table/tbody/tr/td[2]/span/app-generic-cell/div/app-generic-cell-text-input/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e7ca6ce-b9cf-411f-abab-1fb8b21c06c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-show-onhover ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>42a351da-a88d-481f-80e0-2f1818cbde7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ec567fe-4d00-4114-a73a-d8ab4562420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>be96696e-92fa-47f9-9eb8-7fb8f2f54f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-1-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/p-table[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ui-table ui-widget ui-table-resizable ui-table-resizable-fit&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;textCenter colonne-generic-table gtbl-td ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/app-generic-cell[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;component-container-root&quot;]/app-generic-cell-text-input[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control input-show-onhover ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>42a95405-e26f-4ac7-ba5e-7d9c204c1361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>60c0927c-7329-4c1a-bb37-480d66650400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-1-content']/div/p-table/div/div/table/tbody/tr/td[2]/span/app-generic-cell/div/app-generic-cell-text-input/input</value>
      <webElementGuid>f9fc2a91-e55d-4098-8b55-b609bd86d733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-generic-cell-text-input/input</value>
      <webElementGuid>64444bf4-cc49-4743-9c94-e08e128fe900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>01d931fc-28df-476c-adfd-9bfbf3e67bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
