<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer_Order_Reference</name>
   <tag></tag>
   <elementGuidId>bbc9fe31-9154-4b63-900c-e866c3a067d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerOrderReference&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerOrderReference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b26d31f-8237-4723-b958-92a49559812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d8c34c84-f5cb-4a1d-8e9f-fa8e3d74acd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerOrderReference</value>
      <webElementGuid>b1ec67f3-c591-4e1a-868c-92ea327cc963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d1014f0-c70a-4b8c-a6bc-2c6dcfaec1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-order-creation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-padding&quot;]/div[@class=&quot;form-host&quot;]/div[@class=&quot;form&quot;]/app-order-creation-form[1]/div[@class=&quot;create-wf-root form-card&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width&quot;]/div[@class=&quot;wf-step&quot;]/app-order-step-reference[1]/div[@class=&quot;form-root no-padding&quot;]/div[@class=&quot;content&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;margin-bottom-15&quot;]/div[1]/fieldset[1]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 margin-top-15 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 padding-right-0&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>e488ff65-0a46-4ef7-bc97-b551120a4280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerOrderReference']</value>
      <webElementGuid>c139bb55-c4fc-4157-b73e-772fa2ce5001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-order-creation/div/div/div[2]/app-order-creation-form/div/div[2]/div/div/div[2]/app-order-step-reference/div/div/form/div/div/fieldset/div/div/input</value>
      <webElementGuid>c6f35d47-74a2-44da-a173-2efb2389336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>fe13e9e9-0687-445c-a6cd-6ceda40961aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'customerOrderReference' and @type = 'text']</value>
      <webElementGuid>2236d781-e5fd-46ea-a69e-9cd4f23d9741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
