<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hi, My Tower</name>
   <tag></tag>
   <elementGuidId>9c2474d6-8600-4347-a113-4429890b63c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownBasic1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownBasic1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32795ef6-6daf-42d6-9195-dd2e63c6592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4c80674-72c4-41d9-9616-06656ddb29d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle fw600 p15 pb0 cursor-pointer dropdown-toggle</value>
      <webElementGuid>6ad04a7a-b840-40a7-b334-b2927bb3269f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>5ab4a05c-7725-4f1a-9dfc-861292bea391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownBasic1</value>
      <webElementGuid>993da26f-f4fa-4537-9d8a-33ff0bee56f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69ceddd2-54c6-49f2-9994-b05e32ec7b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hi, My Tower </value>
      <webElementGuid>b244f853-9cdf-4d0f-a4f3-31954c3e1a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownBasic1&quot;)</value>
      <webElementGuid>b2949e40-4a64-4129-84d5-25d3c151b0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dropdownBasic1']</value>
      <webElementGuid>7e9d7afd-ea64-4c15-a710-2248407446b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/a</value>
      <webElementGuid>ab5606b4-b700-422d-8991-d0bafc69585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select user...'])[1]/following::a[4]</value>
      <webElementGuid>08e5a206-5d71-4b46-ad48-c3cc46744d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/preceding::a[1]</value>
      <webElementGuid>fe8637ce-8cd6-4d1f-bd46-da717f0c4820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/a</value>
      <webElementGuid>a128a796-f19e-49e5-8e0e-f19871143e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dropdownBasic1' and (text() = ' Hi, My Tower ' or . = ' Hi, My Tower ')]</value>
      <webElementGuid>fe7ebdd6-474a-4706-a4e9-ee0cbfbe9282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
