<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>9a26a35d-d099-4371-a9a8-76f4a3591ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64e3055c-6759-401f-9e9b-40e79e34b323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/company</value>
      <webElementGuid>63ee117a-a4b8-4da9-8da9-a12ddfdcf08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/company?tab=company</value>
      <webElementGuid>ec7dcc75-701d-4333-9e29-efcce573ead3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>d371b96a-201b-4139-ac68-9e99ac531beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/nav[@class=&quot;opened d-flex-ai-c animated fadeInDown navbar-header navbar-fixed-top navbar-shadow user-controlTower ng-star-inserted&quot;]/div[@class=&quot;header-items d-flex-ai-c d-flex-jc-fe&quot;]/div[@class=&quot;user-connect_items d-flex-ai-c d-flex-jc-sb&quot;]/ul[@class=&quot;navb navbar-right&quot;]/li[@class=&quot;right-menu-dropdown user-options padding-right-5-important menu-merge show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/ul[1]/li[@class=&quot;dropdown-item listElement&quot;]/a[1]</value>
      <webElementGuid>c638199e-202c-48d9-ac82-813a30004833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]/a</value>
      <webElementGuid>91fd9229-6d17-44c5-b82d-a76fe03171f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>fe9d50cf-c79f-431c-a064-0766c3ffbfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/following::a[1]</value>
      <webElementGuid>65b03eed-fcaf-4cd5-92be-fcfb6b30396f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, My Tower'])[1]/following::a[2]</value>
      <webElementGuid>d6f6bfdc-331b-4caf-afbb-d08b79146bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My community'])[1]/preceding::a[1]</value>
      <webElementGuid>00659e47-0aad-41da-b983-6029ee3f46df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[2]</value>
      <webElementGuid>98360c0b-0719-4875-8feb-969ba328f9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>a15b6455-8eb0-40d8-81b7-0b933bada53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/user/settings/company?tab=company')]</value>
      <webElementGuid>ee31c96b-098e-402e-8636-af8589984df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>03c31641-1f2c-4cae-a805-63c459513518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app/user/settings/company?tab=company' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>ecbd5574-1272-49fb-ad3e-59a8b5355df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
