<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>2a3d54ee-408e-4c69-84bd-51ecf4ca7508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pull-right > div > button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc9c201f-1a42-45f0-8c46-cf4c5ae2dcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>da49769f-81be-4561-8a5d-74450bcfe3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3007eec8-f60f-4313-9735-71e9f505fe9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update </value>
      <webElementGuid>e993fa64-0e7b-4bb1-a03f-35332514a851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-account[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid padding-4-10&quot;]/div[@class=&quot;col-md-6  margin-left-10 margin-right--10&quot;]/div[@class=&quot;margin-top-5 margin-bottom-5&quot;]/fieldset[@class=&quot;fieldset&quot;]/div[@class=&quot;col-md-12 col-xs-12 body-table&quot;]/form[@class=&quot;space-rows row ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;col-md-12 margin-bottom-10&quot;]/div[@class=&quot;pull-right&quot;]/div[1]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>5747f219-86ba-4741-b6c1-0b4fdcf6d483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>60144e93-109e-4384-a1ff-39f85b19cb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[2]/app-settings-my-account/div/div[2]/div[2]/fieldset/div/form/div[2]/div/div/button</value>
      <webElementGuid>3f658c5c-e88f-4511-895a-0e8a0dd939c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select your language :'])[1]/following::button[1]</value>
      <webElementGuid>a76b228b-2700-45bf-88d3-f43f700a461d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My preferences'])[1]/following::button[1]</value>
      <webElementGuid>db805d9b-47e7-4b53-a08c-20fee92cfbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>4c192e37-f980-4ac1-9019-cb22f90bc8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Update ' or . = ' Update ')]</value>
      <webElementGuid>161869e7-df50-4be6-b383-c20156b498c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
