<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Settings</name>
   <tag></tag>
   <elementGuidId>59af651a-6738-4eb8-8b09-49bed7ae98ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2941b1fe-9bec-436f-9ead-e32a809aba8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item listElement</value>
      <webElementGuid>bb8be2b9-6415-4701-b9b7-c052c3764709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>5152986d-728d-419f-932b-c38c82fc26d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/nav[@class=&quot;opened d-flex-ai-c animated fadeInDown navbar-header navbar-fixed-top navbar-shadow user-controlTower ng-star-inserted&quot;]/div[@class=&quot;header-items d-flex-ai-c d-flex-jc-fe&quot;]/div[@class=&quot;user-connect_items d-flex-ai-c d-flex-jc-sb&quot;]/ul[@class=&quot;navb navbar-right&quot;]/li[@class=&quot;right-menu-dropdown user-options padding-right-5-important menu-merge show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/ul[1]/li[@class=&quot;dropdown-item listElement&quot;]</value>
      <webElementGuid>41fbcd16-d120-4bfc-aaae-9111b4ba5512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/nav/div/div/ul[4]/li/div/ul/li[2]</value>
      <webElementGuid>4a2f2e36-b6f3-437b-a572-6a7507ae34d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/following::li[1]</value>
      <webElementGuid>c69270e2-8b4e-4aaa-9c46-273b49dabf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, My Tower'])[1]/following::li[2]</value>
      <webElementGuid>2b1060d3-985c-4a4c-851c-3ed9996910d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My community'])[1]/preceding::li[1]</value>
      <webElementGuid>66860f90-8ed0-4300-b6bb-7789677136e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]</value>
      <webElementGuid>a0fdec2b-795e-4e5c-a9ed-ae6c6317727b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>1c5c42b8-e910-485b-ab95-e1e7b25a619b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
