<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>2a959493-494f-440c-a873-3185f17745e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='language']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;language&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a390b635-f97e-4a3d-a02f-d91c1e35c155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e905860-e570-4585-879f-38fa6418c3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>language</value>
      <webElementGuid>1462b169-9bb5-4f92-8185-630b343c5d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnglishFrançais</value>
      <webElementGuid>4d713db7-72d8-4e2e-9c6c-428642d276a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-account[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid padding-4-10&quot;]/div[@class=&quot;col-md-6  margin-left-10 margin-right--10&quot;]/div[@class=&quot;margin-top-5 margin-bottom-5&quot;]/fieldset[@class=&quot;fieldset&quot;]/div[@class=&quot;col-md-12 col-xs-12 body-table&quot;]/form[@class=&quot;space-rows row ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;col-md-12 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-7 padding-0&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a715eb28-8da5-4b77-9c2f-827c27f375f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='language']</value>
      <webElementGuid>f53a1b0a-5e4e-470f-ac4c-ecad1de3b593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[2]/app-settings-my-account/div/div[2]/div[2]/fieldset/div/form/div/div/select</value>
      <webElementGuid>8811939c-f720-4ffe-ad29-75ab4d47781e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select your language :'])[1]/following::select[1]</value>
      <webElementGuid>6abdf371-4fbf-4d0e-a4d1-1fdfde93a192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My preferences'])[1]/following::select[1]</value>
      <webElementGuid>b50cfd6e-14d4-4d6c-b1f0-5dd56809f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/preceding::select[1]</value>
      <webElementGuid>58378aa7-7177-4e30-b18c-7f61facf9731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c455187d-ed3a-4039-b4a5-f03a8b8a2188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'language' and (text() = 'EnglishFrançais' or . = 'EnglishFrançais')]</value>
      <webElementGuid>98b4da7b-5724-4d40-8c4a-2cf7dc624f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
