<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next1</name>
   <tag></tag>
   <elementGuidId>15ecbac1-d8fb-415f-b963-3a80173945f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-dark-login.login-buttons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div[2]/div/div[2]/aw-wizard/div/aw-wizard-step[1]/form/div[9]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9730af3e-092b-486e-af94-3709d8b9d81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark-login login-buttons</value>
      <webElementGuid>91900e06-7bcb-41d3-a4f3-fc1c0c1e0efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Suivant </value>
      <webElementGuid>091ae65f-804d-4e70-891a-4df29dad9a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;login&quot;]/div[@class=&quot;sides-wrapper&quot;]/div[@class=&quot;right-side&quot;]/aw-wizard[@class=&quot;creat-account__steps horizontal&quot;]/div[@class=&quot;wizard-steps horizontal&quot;]/aw-wizard-step[1]/form[@class=&quot;col-md-12 padding-4 ng-dirty ng-touched ng-valid&quot;]/div[9]/div[@class=&quot;col-md-12 padding-0 text-right&quot;]/button[@class=&quot;btn btn-dark-login login-buttons&quot;]</value>
      <webElementGuid>27c7a089-e909-4323-a41d-a949e76f006d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[2]/aw-wizard/div/aw-wizard-step/form/div[9]/div/button</value>
      <webElementGuid>808b5b8b-e1f4-49f9-881b-4828c8820756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veuillez saisir le meme mot de passe'])[1]/following::button[1]</value>
      <webElementGuid>c3a2de17-2809-44c4-bc02-ec5db15fbc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmer mot de passe'])[1]/following::button[1]</value>
      <webElementGuid>308b908b-9c4a-419f-a94f-bc2d6de8dd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIREN'])[1]/preceding::button[1]</value>
      <webElementGuid>213fdf5c-e323-4410-b751-6eff07f809a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veuillez insérer le SIREN, pour que nous puissions vous mettre en relation avec votre société'])[1]/preceding::button[1]</value>
      <webElementGuid>e5db1b71-4a9f-46b2-b197-8733d82cc440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suivant']/parent::*</value>
      <webElementGuid>d87d6dc7-b094-4d3f-a38b-f5cd90fe403c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/button</value>
      <webElementGuid>a2bcaa1a-c5ed-447a-8e65-630ffe0ad54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Suivant ' or . = ' Suivant ')]</value>
      <webElementGuid>c1f885c9-e2e2-4402-be2b-717336c45574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
