<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Congratulations Your MyTower account is created</name>
   <tag></tag>
   <elementGuidId>6a85bb77-07d3-4459-b076-bd0e57592292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-body.text-style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c351186-165e-4a16-8741-8dbcfaec494e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>7679cca5-54d2-42c8-a65f-ef7c9b528c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>0ecc50a7-1af5-4b6e-9693-9e74c6198d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>f08a80d0-ab01-4850-b348-55d3c8fa545a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3819b6ed-ad46-4c97-959f-9333177ce0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>47be1757-2b64-4b9b-a60b-70140308685c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>6040834a-a3af-4ce4-922c-88b714618a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>4093b717-a137-4376-a36f-ddbe9200cfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>315c59ee-a05d-496d-bec6-9d862af1d6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>36fd1175-f0a8-4c4d-88c9-54a5955809de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>a0458f02-75c2-42a9-84bc-32bdee8e4afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>8a75233c-8848-4ba9-b1df-410ea621cedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74c821ac-07d5-414b-8b62-0837ed09a904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>06eab039-2b43-41a7-a7b8-1c2054f01604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>d7c556f9-812d-46c7-9e7d-3a18b6ce504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>014b80af-97a0-4ebb-b1cd-cc6d7a2b2e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56e886df-461e-4b8e-9538-791e854b7a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>085e4141-6fa2-4b55-8c1f-6b650f67fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>39c30f77-6348-4d20-8e5e-c48e181d94ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>a8163aec-8a6a-4b56-b1cb-1695d60ddee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9809650-b6f9-4c9a-bbe0-c83daae3a356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>487d07b2-e372-464d-8b46-fb5c03023b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>c15094b8-97ff-487d-84b5-f0e8a4a798ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>cabddede-fb3b-45b1-b01f-474be460a71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb8e74a9-3efd-4027-a98e-f0c2916ca4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>7c2f63ec-4a10-465e-9c78-bb1b56f49134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>f798f9d1-e984-4c33-99c5-30cfea086c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>191cb9e6-fc41-4a0f-9e50-720670fae348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93debf7b-cf6b-4125-b1fd-ed409f635650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>9c298696-ece8-4338-90b4-d8c2606e01e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>59ecb2d0-6e1d-40af-8189-156aeef601e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>ee385027-5701-446d-aac6-96b2a6da57ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ca5ecc9-0b0e-4313-9309-b731238fa754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>88ad6c46-6189-4e0a-8768-34ce6f9cd922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>f043481a-5b27-4dba-98ee-513e2f869c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>0a8b042d-a363-4ee3-ad89-7d6a86cf7695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a066fec2-9a42-492e-862e-4cf02f173995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>5d17d5be-d322-4620-b6b1-6c7403cb8aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>135fa0e0-ae0b-4535-80a2-01c9d21040b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>f5ded815-bd2e-447c-b8a5-ece1bf23c36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d5ffdb4-7076-448e-bf57-47b5f8456d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>64bbf0e5-1043-42d8-947a-4857ecc741af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>bb5bd0dd-9b71-4822-a4d5-2d195956aa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>9440a2c7-8d7a-47b0-b130-84dda1560d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c01e8a5c-e691-46f1-824a-b662d11edfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>229f35bf-f8d2-4bdd-b405-c6cf0574cf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>f7a14786-57d5-43ec-a0d5-ab658f5cee40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>ca306674-08b0-46e3-9144-d46773dfd1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4610c54c-bf15-43cb-bdb9-dc6f40bd5c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>2b62b1cd-c4e8-449f-b28c-eff48aada1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>e2090514-fb87-431c-89d9-a8d6912c5eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>17c46411-912d-4d49-9459-7121287c04cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8356c9ed-3d28-46ee-832a-67e25894bcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>5818ad42-566b-48e6-87b8-255fd49b4fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>c1436e14-91e7-412a-aac0-5c6ca846a5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>97b62a82-3ce8-4758-a878-6b8a0c8b8ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2499d44e-ca63-467a-a6a8-c6cb2288d393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>98edc29d-4d6f-48d3-be6a-a76f56ec9cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>43d512e2-2cbd-4ede-8c42-b87b443f4db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>c20c4404-0d4f-4874-b3f0-2623247081ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3691eb87-5667-4b6b-b4a6-f4faa2036653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>eeed8fce-afef-42a1-aabc-12ebdc4d3ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>46ef54b3-44ae-4c1e-b4e6-36b8222efb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>59f66c82-04f7-4c1b-b650-785b918602f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44e8da35-ca9f-4060-932f-79360916bad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>03c82b1d-92f7-4ea2-9f97-3c7791733cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>a8dcb3c0-007d-4964-ae7a-3c4482b0affd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>e6884985-17d5-4ad5-9a61-a71e31bb7e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27106a75-367f-4420-959b-58a2e2376499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>11339c05-13ff-44c7-94a1-bc84699d16e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>2d3b32b0-7be0-47d2-8541-b5b3ef37d83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>54ed112a-9ad8-41ec-9e5f-943f054503a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de48df06-935f-48e8-a76a-d71fde0be7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>a27ab6b7-5072-4e37-b4c6-e21c39c88ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>cd3a91ac-ad86-4833-87e2-388f840ec44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>e5d369ce-61bd-4d2e-83c4-2099f605db9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd277d1f-38db-4e25-a290-869c1f3d4163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>eebec8df-9ce0-4eed-a9ba-adff8db56485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>86769851-4880-4482-80a4-96f96254be48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>4608c26a-cbc7-45b8-8b38-4f3ac53bed58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfca309e-4677-499d-86ac-6ec9e92cbf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>49cd4f6a-4583-45db-8ebf-446bf1cc7c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>ac726cc3-0c53-468f-b5b9-14a6f1d7522f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>49821d1e-88ae-4c56-8d67-a79399fb205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60289c7c-21b9-47fb-8376-067f4b3de309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>42d70a49-be7f-4ef4-83b4-ea53649bac2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>30b6e110-8fba-4c08-82bc-e205e581a9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>95aff75f-115a-4544-83ba-bc876995f31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27482ac0-701d-4818-aaa7-1c482e93910a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>da91518b-0199-4ef9-a927-13e0c820011d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>ea8cd54c-f682-47ed-b7b7-2e344aea1185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>3f07028a-e2bd-4a0d-991e-f2439ba94da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32718ea9-fba8-40dd-a8a5-866955fef285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>ffef26e9-ee81-4eca-8816-962c6b25f912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>fb2a8653-fc51-4a22-9a5a-6d3510737582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>97c43a60-d73a-4e6c-848d-746ec4899070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03ddffe5-a900-4d9c-9c5e-3d220a5a5e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>a57b5050-544e-4e1e-ad92-71ebf4cf44a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>5616ca0a-23fb-4d95-98ec-2fc4fec7d852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>078c6e3e-f180-407c-ac6a-a76d9366634e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e72ea920-baae-4eac-b0e2-cfb0537de769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-style</value>
      <webElementGuid>e35df963-1d95-43d9-84c9-28e2a3b49f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Congratulations! Your MyTower account is now created. An activation link has been sent to you by email </value>
      <webElementGuid>7d7e0278-9675-4327-8774-9df923ace74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;background default-theme&quot;]/app-root[@class=&quot;default-theme&quot;]/app-modal[1]/div[@class=&quot;modal modal-backdrop ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body text-style&quot;]</value>
      <webElementGuid>6b3cf0f7-6169-482a-a86b-bef87ade2fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      <webElementGuid>9b534d9f-5cb9-4b4c-9e1f-c40dbc858d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::div[6]</value>
      <webElementGuid>630fae0f-7b3b-4868-af58-4f4922e1e707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[1]</value>
      <webElementGuid>2dd91c3b-5c6b-4ca5-bf3e-ed3b5050391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Congratulations! Your MyTower account is now created. An activation link has been sent to you by email']/parent::*</value>
      <webElementGuid>859f6f63-1519-4d9b-b9ad-398a3a11f031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modal/div/div/div/div/div[2]</value>
      <webElementGuid>2039a97e-70b3-4fc0-a145-c28177c6fd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Congratulations! Your MyTower account is now created. An activation link has been sent to you by email ' or . = ' Congratulations! Your MyTower account is now created. An activation link has been sent to you by email ')]</value>
      <webElementGuid>22f495d8-cae4-4cf9-84bb-e48b4e9777f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
