<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Signin_button</name>
   <tag></tag>
   <elementGuidId>efe06e47-7c12-4244-b7a4-91e8c1058d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@routerlink='/inscription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@routerlink='/inscription']</value>
      <webElementGuid>03c0547b-bb55-40c9-a0b1-5df25d7721b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
