<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>1cedc551-6b2e-427d-906e-fff8010551d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-remove.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-0-content&quot;]/div/p-table/div/div[1]/table/tbody/tr[1]/td[1]/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ba4ac802-b070-44fb-93c6-a6837c1d34f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-remove ng-star-inserted</value>
      <webElementGuid>9012c98d-f2d6-46af-bcc8-c67b53055f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5c6bbb54-1c4c-47da-9b4f-a4a1620a5d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/p-table[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ui-table ui-widget ui-table-resizable ui-table-resizable-fit&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;width-70-important text-center gtbl-td ng-star-inserted&quot;]/i[@class=&quot;fa fa-remove ng-star-inserted&quot;]</value>
      <webElementGuid>2ad8145c-fca3-449f-9506-0c2988bc94ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/p-table/div/div/table/tbody/tr/td/i[2]</value>
      <webElementGuid>4022eb48-b1db-4130-8437-c61b9c8fe61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>c45f3f57-d2f2-4712-8e3d-4f1f275482c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Delete']</value>
      <webElementGuid>10abd4e3-dea8-4de1-b4ac-80265a1cf074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
