<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_settings_content</name>
   <tag></tag>
   <elementGuidId>37aad8a6-9a2f-4ddc-93db-065e5ebac9a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.settings-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-corp/app-settings/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80874e41-762b-42da-a737-33ad8f391c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>settings-content</value>
      <webElementGuid>6d55dcd1-ed56-46a2-9914-8dc9b6181950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ui-btnui-btnui-btnui-btnFlagsReferenceNameIconSelect icon...×Color Add  Cancel </value>
      <webElementGuid>38bbb7b9-9bdc-4c29-947e-d4b166733c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]</value>
      <webElementGuid>54849f1a-c640-4631-a8c7-24bb2dfd2c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-settings/div/div[3]</value>
      <webElementGuid>5603e4bd-dff1-4aa8-9d52-84752ae246d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flags'])[1]/following::div[1]</value>
      <webElementGuid>739078e4-0dac-47d7-862e-1f9904087ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My company'])[2]/following::div[1]</value>
      <webElementGuid>f9562c27-fcf2-4c14-b8fa-1318f4077af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-settings/div/div[3]</value>
      <webElementGuid>e9b672fd-f114-4e97-abb7-7ab0fc43e7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ui-btnui-btnui-btnui-btnFlagsReferenceNameIconSelect icon...×Color Add  Cancel ' or . = 'ui-btnui-btnui-btnui-btnFlagsReferenceNameIconSelect icon...×Color Add  Cancel ')]</value>
      <webElementGuid>8700e2ec-f013-4f55-a2a7-6da0abe565a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
