<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color</name>
   <tag></tag>
   <elementGuidId>30342e1c-5ab5-40ad-874b-6c0967c809c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-colorpicker-hue-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-0-content']/div/form/div[2]/div/div[4]/div/p-colorpicker/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd6ab634-1d27-436b-b784-33cff8cd3000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-colorpicker-hue-handle</value>
      <webElementGuid>f57cfc44-3834-4d8e-a470-cbe5a0f5de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 new-formcontrol&quot;]/div[@class=&quot;col-md-12 padding-left-0-important padding-right-0-important&quot;]/p-colorpicker[@class=&quot;ng-tns-c31-4 ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;ng-tns-c31-4 ui-colorpicker ui-widget ui-colorpicker-overlay&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c31-4 ui-colorpicker-panel ui-corner-all ui-colorpicker-overlay-panel ui-shadow ng-star-inserted&quot;]/div[@class=&quot;ui-colorpicker-content&quot;]/div[@class=&quot;ui-colorpicker-hue&quot;]/div[@class=&quot;ui-colorpicker-hue-handle&quot;]</value>
      <webElementGuid>360da411-34b8-449b-8c08-bee2ac85ec6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div[2]/div/div[4]/div/p-colorpicker/div/div/div/div[2]/div</value>
      <webElementGuid>18ba012f-753f-47e9-893b-11622f428784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>e3abde8f-6be6-4f5c-b975-e884b27e5f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
