<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon</name>
   <tag></tag>
   <elementGuidId>ea0c323e-97ce-4404-973b-4ccdc389fcd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a81a8526c05c-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ng-option ng-star-inserted'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b12f457-c7f1-4f0d-905d-58fa06771423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>75522e2b-6a76-456a-9c72-5a5f1c697f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7ac6b6bb-d0d8-4b1b-8369-6a43281079af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f49612a-60f4-4f9c-ab55-e117daaa17cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a81a8526c05c-0</value>
      <webElementGuid>ecaa2b9a-1c87-4cf0-9cb4-8f6d5a2da76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a81a8526c05c-0&quot;)</value>
      <webElementGuid>45ebdf4f-1987-492b-a3cb-2260a44f201e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class='ng-option ng-star-inserted'][1]</value>
      <webElementGuid>d308b028-e147-4bd4-942a-6c7438de7829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a81a8526c05c']/div/div[2]/div</value>
      <webElementGuid>d8501dc7-5484-45f9-ae8c-3e6c747036ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select icon...'])[1]/following::div[5]</value>
      <webElementGuid>66dabcef-7524-4831-9eb5-e5f1cdc06e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Icon'])[1]/following::div[9]</value>
      <webElementGuid>eadcd351-bc96-4fca-88d9-b299f973a3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::div[23]</value>
      <webElementGuid>c3b9eb38-8fb9-42bc-a496-b3b3d7b08700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::div[26]</value>
      <webElementGuid>496dc6e5-58c4-47e2-9b29-8dea74b11084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>57f9ca42-16f1-4f37-98a8-48463da5e390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a81a8526c05c-0']</value>
      <webElementGuid>99f0d6cf-15bd-4cdb-b4b0-cda1008177ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
