<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Color</name>
   <tag></tag>
   <elementGuidId>fdd0dca2-69f4-4bd1-ac24-20dcb933a752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ui-colorpicker-preview.ui-inputtext.ui-state-default.ui-corner-all.ng-tns-c31-7.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c72f879-a7c4-44e1-8f6e-b55a518cdcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-colorpicker-preview ui-inputtext ui-state-default ui-corner-all ng-tns-c31-7 ng-star-inserted</value>
      <webElementGuid>ca30ddf4-b9a5-43a5-876e-351f219c3db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f2241a9c-623d-484e-885b-059c7f8778a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95354c47-8527-482d-acbb-cfe811b88a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-1-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-pristine ng-star-inserted ng-invalid ng-touched&quot;]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 new-formcontrol&quot;]/div[@class=&quot;col-md-12 padding-left-0-important padding-right-0-important&quot;]/p-colorpicker[@class=&quot;ng-tns-c31-7 ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;ng-tns-c31-7 ui-colorpicker ui-widget ui-colorpicker-overlay&quot;]/input[@class=&quot;ui-colorpicker-preview ui-inputtext ui-state-default ui-corner-all ng-tns-c31-7 ng-star-inserted&quot;]</value>
      <webElementGuid>f07b9668-ec8a-44c3-8f40-8ec02a2cc291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>1fb6d093-8f7d-4d2b-97a8-62274be07ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-1-content']/div/form/div[2]/div/div[4]/div/p-colorpicker/div/input</value>
      <webElementGuid>7a7b37b6-09f3-4a58-a818-b216ad91555d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-colorpicker/div/input</value>
      <webElementGuid>f18bd957-717b-42ca-a921-32d28d0a4f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>160ab0da-937f-40e4-81eb-64e18cfde2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
