<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference</name>
   <tag></tag>
   <elementGuidId>aa861345-df28-49b0-83bc-fe8b6f3fa1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reference&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>050c56d1-f811-4965-84ba-f1734d544d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2c5fe750-d4e1-49c1-82f7-b0aba1c3c343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>966c5712-c7dc-434d-a5d4-7efe5b3b1b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77cd5da9-63d6-4745-80bd-54b4f7836cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-1-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;generic-default ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;form-content col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 new-formcontrol&quot;]/div[@class=&quot;col-md-12 padding-left-0-important padding-right-0-important&quot;]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>a27de7bd-cfd5-4a60-a5ca-f61a5fa58199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reference']</value>
      <webElementGuid>1b684c77-f395-442b-b20b-861309e933c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-1-content']/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>b1026d39-88bc-48d4-b745-7d30f0a5ea4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>670b18b5-fb3e-455c-a10e-9d1534f8dc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reference' and @type = 'text']</value>
      <webElementGuid>53310800-5fcf-4171-9251-1ffa18465354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
