<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm_Delivery</name>
   <tag></tag>
   <elementGuidId>1a01ee58-2222-4cee-8726-d37273947a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-header']/app-header/div/div/div[2]/div[3]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1e937bc-4719-4b33-94ca-73bcaa3a1d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-title</value>
      <webElementGuid>1d01ad67-5511-40c0-bf85-3570f14cecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>63178e22-2d6f-4b3f-9975-677ff22e4d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/div[1]/div[@class=&quot;actionbar-wrapper&quot;]/div[@class=&quot;btn-action-wrapper&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/button[@class=&quot;btn btn-xs btn-primary ng-star-inserted&quot;]/span[@class=&quot;sidebar-title&quot;]</value>
      <webElementGuid>9e1f3a42-2ada-4217-8b06-674767c6aa89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/div/div/div[2]/div[3]/button/span[2]</value>
      <webElementGuid>f9a74e19-8872-47ae-9d22-49f390970c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/following::span[2]</value>
      <webElementGuid>cfbc9e85-47c5-4e2a-b220-5349c53a40cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSY-V00007'])[1]/following::span[4]</value>
      <webElementGuid>ac2f3059-abd8-41f2-beb9-1bae740356eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>6557111c-ce21-4ad6-8601-999ac23654da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::span[4]</value>
      <webElementGuid>2d8f765b-447b-436d-b828-8620e62a8ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>60f2704c-e781-4b2f-9fd3-9b2bcd65f898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>ef688a2d-1c15-4b2e-933f-130e112f22cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>9727a8dd-67c0-4312-94d2-2da216a33df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
